### ISSUE TITLE
Options menu: Changing application language doesn't change language of buttons

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#102]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

Even though we changed the application's language, Ok Cancel and Apply buttons remained in our native language:
![image](https://user-images.githubusercontent.com/39709348/149844692-45efd688-cf6b-4ce0-96d9-6b8456ef6283.png)

Expected result: Button's language should also change

Used version: NanaZip 1.0 x64

**Comment by MouriNaruto** [comment]
Starting with NanaZip 1.2, the language page in Options dialog had been removed because NanaZip will follow the language settings from Windows itself.

So, close the issue.

Kenji Mouri

**Comment by github-at-kim-homann-dot-de** [comment]
That is absolutely not satisfactory. I have a German Windows installation, but I have set all my installed applications to have English UIs bc German translations are often bad and, most of all, not googlable. *Every* application aside from NanaZip has a per-application language setting, even Microsoft's own applications do. So as NanaZip cannot be switched to English without switching the entire OS to English, and 7-Zip doesn't support the new Windows 11 context menu, the best solution for me was to uninstall NanaZip and deactivate the Windows 11-style context menu, so I can use 7-Zip with English UI again.
