### ISSUE TITLE
Open inside option should be visible only for folders and archives

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#108]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

When clicking Open inside options in NanaZip's explorer's context menu on different types of files than folders and archives nothing happens, so therefore this option shouldn't be shown.

![image](https://user-images.githubusercontent.com/39709348/149968656-815237dc-f9d7-4547-9910-8ef40042d461.png)

Used version: NanaZip 1.0 x64

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Rebuilding XAML UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
