### ISSUE TITLE
Context menu: Open, Properties, Delete options shouldn't appear when clicking on blank space

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#109]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

When right-clicking in NanaZip's explorer's blank space the context menu is shown. There appear options such as Open, Properties, and Delete, which don't do anything after clicking, so therefore they shouldn't be available.

![image](https://user-images.githubusercontent.com/39709348/149969308-a990146d-ef38-4dd1-931a-f909e8c46ba6.png)

Used version: NanaZip 1.0 x64

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Modernizing UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
