### ISSUE TITLE
怎么安装啊？？？？？？？？

### ISSUE THREAD

**Issue by baijixiaozi** [M2Team/NanaZip#11]
C:\Users\Administrator>Certutil -addStore Root "[The path of MouriNaruto.cer]"
Root "受信任的根证书颁发机构"
DecodeFile 返回了 系统找不到指定的文件。 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: -addstore 失败: 0x80070002 (WIN32: 2 ERROR_FILE_NOT_FOUND)
CertUtil: 系统找不到指定的文件。

**Comment by MouriNaruto** [comment]
很显然你没看懂英文……"[The path of MouriNaruto.cer]"是要让你填这个文件的路径的

反正商店也已经成功提交 Preview 2 版，于是可以直接去商店安装

**Comment by baijixiaozi** [comment]
弄好了。菜鸟多。你没说清楚。我删掉商店了



---原始邮件---
发件人: "Kenji ***@***.***&gt;
发送时间: 2021年10月5日(周二) 凌晨4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [M2Team/NanaZip] 怎么安装啊？？？？？？？？ (#11)




 
很显然你没看懂英文……"[The path of MouriNaruto.cer]"是要让你填这个文件的路径的
 
反正商店也已经成功提交 Preview 2 版，于是可以直接去商店安装

**Comment by baijixiaozi** [comment]
---原始邮件---
发件人: "Kenji ***@***.***&gt;
发送时间: 2021年10月5日(周二) 凌晨4:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [M2Team/NanaZip] 怎么安装啊？？？？？？？？ (#11)




 
Closed #11.

**Comment by baijixiaozi** [comment]
没有exe版本吗



---原始邮件---
发件人: "Kenji ***@***.***&gt;
发送时间: 2021年10月5日(周二) 凌晨4:58
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [M2Team/NanaZip] 怎么安装啊？？？？？？？？ (#11)




 
很显然你没看懂英文……"[The path of MouriNaruto.cer]"是要让你填这个文件的路径的
 
反正商店也已经成功提交 Preview 2 版，于是可以直接去商店安装

**Comment by MouriNaruto** [comment]
@baijixiaozi 

暂时没有 exe 安装版本，NanaZip 应该会在 1.0 正式版的时候提供专用的部署工具

毛利
