### ISSUE TITLE
Error appears when trying to create lizard archive

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#110]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

Real result: When trying to create a lizard archive, an error message appears

Expected result: Archive .liz is created

Used version: NanaZip 1.0 x64

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NanaZip/commit/3f10b7def229968b4066ef8f405860a82fe86833

This commit should fix this issue. Please wait for the next NanaZip release. The issue is closed.

Kenji Mouri
