### ISSUE TITLE
选中文件的问题【bug】

### ISSUE THREAD

**Issue by Amhertx** [M2Team/NanaZip#116]
按详细信息查看文件的时候，名称短的无法被框选，一定要框选到名字上，按列表类型查看文件则不会，有个小建议：可以做成windows那种框选吗，按照占用的行来框选

![image](https://user-images.githubusercontent.com/46993971/153358995-8ccaf8ac-5a47-44ce-b3dd-14cebe0792fd.png)
![image](https://user-images.githubusercontent.com/46993971/153359544-364d2e76-2f0f-4402-a910-93db93fc327d.png)

**Comment by MouriNaruto** [comment]
这个不是 Bug，你需要去`工具` -> `选项` 里面开启整行选择功能

![image](https://user-images.githubusercontent.com/10867563/153362535-cd70d2af-4bc7-44fa-a293-c5bda177911b.png)

毛利

**Comment by Amhertx** [comment]
> 这不是Bug，你需要去选择`工具`->`选项`里面开启整行功能
> 
> ![图片](https://user-images.githubusercontent.com/10867563/153362535-cd70d2af-4bc7-44fa-a293-c5bda177911b.png)
> 
> 毛利

丢脸了属于是，没研究明白😂，谢谢
