### ISSUE TITLE
在根目录下右键时100%导致程序崩溃

### ISSUE THREAD

**Issue by lychichem** [M2Team/NanaZip#12]
![image](https://user-images.githubusercontent.com/9316590/135963590-31e3b277-9e72-4625-8ed7-83aa8b4a5077.png)
如图所示，在这一级根目录下右键任何项目均会导致程序直接崩溃，崩溃报告如图：
![image](https://user-images.githubusercontent.com/9316590/135963730-733a36d1-cbd3-4c8d-b62a-862c9bb01f81.png)
我自己在我win11的机器上操作三次每次都可以复现，同学在win10机器上也可以复现

**Comment by MouriNaruto** [comment]
该问题属于已知问题，在 Release 页面写到的奇妙崩溃就是这个

我在等待上游进行修复

毛利

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NanaZip/commit/fb448b3ee2aed000ef0616993fb66fda8108b517

VC-LTL 已更新，问题解决

毛利
