### ISSUE TITLE
Nana zip missing from context menu

### ISSUE THREAD

**Issue by BCorbett0312** [M2Team/NanaZip#120]
I have noticed that if you revert to the old view of the context menu nana zip will be removed from the context menu.  If you revert to the classic view without the show more options then it will be removed.  This just happened recently has i was previously using Nana zip in this mode but it just was removed.  

This however now makes 7zip appear in the context menu where before it didnt.

**Comment by MouriNaruto** [comment]
Maybe you need to provide more detailed information.

Kenji Mouri

**Comment by BCorbett0312** [comment]
if you follow the process to return to the classic context menu as described here https://appuals.com/disable-show-more-options-windows-11/ nana zip is then removed from the context menu.  I dont know what else to tell you.  The application fails to maintain the primary reason it was created when reverting to the view that doesnt use show more options in the context menu.

**Comment by nirajsanghvi** [comment]
+1

@MouriNaruto Note: You can also replicate this without reverting to the classic context menu (though those are the users most affected, including myself). If you right-click on an archive (such as a .zip file) in Explorer, you'll see the NanaZip option. But if you select "Show more options" to switch to the more complete context menu (which @BCorbett0312 and I have enabled via the method posted above as our default), you'll see NanaZip does not appear there. When I have 7zip installed, I see it appear in that classic context menu, and I think the request here is to figure out how to make NanaZip show up there too.

**Comment by hyoretsu** [comment]
Re-bumping this, was looking to switch from 7-Zip ZS to NanaZip, but then it didn't show up in the classic context menu. (The new Windows 11 one is still pretty bad)

**Comment by AndromedaMelody** [comment]
- Fix in #205 
- No new feedback for a long time, so we will close this issue. If the problem is found to appear again in Windows with the latest LCU, you can reopen(and comment) this issue or submit an issue.
