### ISSUE TITLE
No context menu in win10.

### ISSUE THREAD

**Issue by rtrobin** [M2Team/NanaZip#129]
NanaZip: 1.1 ms store
OS: windows 10 21H2 19044.1586

Right click on zipped file, no context menu shown. 

PS. Following [known issues](https://github.com/M2Team/NanaZip#known-issues), I tried deleting then restarting `explorer` processes via Task Manager. It didn't help.

**Comment by MouriNaruto** [comment]
You need to wait for a while because the wsappx service may not be ready. Also, you can try restart your PC.

Kenji Mouri

**Comment by rtrobin** [comment]
I have tried reinstalling nanazip. It didn't help either.

**Comment by Ariane-B** [comment]
Same issue here.

**Comment by SakuraNeko** [comment]
The issue was not reproduced on Windows 10 (OS Ver: 19044.1620). NanaZip 1.1.194.0

Sakura

**Comment by rtrobin** [comment]
The system is upgraded to 19044.1620. Nanazip is reinstalled through ms store. Still, no context menu...

Can you add a button in option tab to fix(reconfigure) context menu in registry?

**Comment by SakuraNeko** [comment]
@rtrobin Your suggestion has been received and we will consider whether to add this content.

We have not yet been able to pinpoint the cause of the problem and we will continue to look into the issue. If you find anything new, please let us know.

Sakura

**Comment by Ariane-B** [comment]
@SakuraNeko To help you understand the issue, would one of the following help?

- Add an option to store much more detailed logs upon installation
- Try a screen sharing session with someone who has the issue

**Comment by SakuraNeko** [comment]
@SkyNinja @Ariane-B I appreciate your continued tracking, but we're still coming up empty at this point, and we'll continue to test to pinpoint the issue.
Also, we are still considering how to build the logging and tracking system, and the tracking system provided by the Microsoft Store does not do a good job of locating these issues.

Sakura

**Comment by kenvix** [comment]
Same problem. I hope that there will be a button to force register context menu manually.

**Comment by AndromedaMelody** [comment]
- Fix in #205 
- No new feedback for a long time, so we will close this issue. If the problem is found to appear again in Windows with the latest LCU, you can reopen(and comment) this issue or submit an issue.

Thanks for your support.
