### ISSUE TITLE
NanaZip使用Temp路径作为拖拽时的临时解压位置的时候是如何实现成功后删除临时文件的

### ISSUE THREAD

**Issue by zhuxb711** [M2Team/NanaZip#132]
Hi NanaZip Team，

我想知道NanaZip拖拽时利用临时目录做中转后是如何检测目标应用是否已经完成处理了这些临时文件并删除临时文件的呢？
我猜测的方案：

猜测1. 临时文件上面设置DeleteOnClose然后把句柄交给目标应用，接受目标应用的DropCompleted事件然后销毁自己的句柄，让Windows去跟踪目标应用上的句柄是否销毁，最后一个句柄销毁时自动删除。
猜测2. 接收DropCompleted事件然后自己直接删除临时文件

那么如果我的应用存在一种情况，就是我会通报Drop已完成但是文件是随后排队处理的，这样的话临时文件已经不存在了，如果我在收到临时文件的时候给它打开一些独占访问的句柄，是否能够阻止NanaZip删除这些临时文件？或者有更加优雅的方式可以让我随后再处理这些文件而阻止NanaZip主动删除临时文件吗？(或延后删除)

**Comment by SakuraNeko** [comment]
@zhuxb711 This is not a issue, I will move your content to the discussion section and we can continue communication there.

**Comment by MouriNaruto** [comment]
这个应该和 Windows Shell 的 API 有关系，只不过这个 issue 也开了很久没有更多讨论了，于是关闭该 issue。

毛利

**Comment by AndromedaMelody** [comment]
- Unlock this issue (archived in discussion[#133](https://github.com/M2Team/NanaZip/discussions/133)).
- For more information, please read #274. Thank you.
