### ISSUE TITLE
能不能在文件校验里添加XXH3和XXH128

### ISSUE THREAD

**Issue by ak8099** [M2Team/NanaZip#136]
老大能否考虑添加XXH3和XXH128，平时用这两个校验文件比较多。
感谢！

**Comment by MouriNaruto** [comment]
相关功能我会考虑的，最早可能会在 NanaZip 2.0 加入

毛利

**Comment by AndromedaMelody** [comment]
- c90017ce1c4dae9c40583c5d27f2077ef0cc59f1
- f502b908dd6b1f124d5808f39f5046acce0bc46c
- 5e9f9057c88529c36a0819cc92a57d24f926f5ff
- 13c44f165531e38e4cdc5b55e6ab0aa088c6e39d

2.0中已实现，故关闭issue，感谢支持
