### ISSUE TITLE
Win11 nanazip preview 闪退

### ISSUE THREAD

**Issue by 1human** [M2Team/NanaZip#139]
Win11版本 22000.593 
nanazip preview 版本 1.1.220.0
而且貌似商店把preview下架了？？
有相同问题的请卸载 。。。

**Comment by MouriNaruto** [comment]
> 而且貌似商店把preview下架了？？

因为和 NanaZip 稳定版看起来类似，只是现在的话问题算是解决了（Preview 版使用了新的图标，正式版的图标也会有所调整）

当然你所提到的问题，我这边应该没法复现，所以只能等待更多信息了

毛利

**Comment by 1human** [comment]
> 
![2](https://user-images.githubusercontent.com/18576031/162882295-29d6b061-570a-4a85-b497-4063b3790363.png)
![1](https://user-images.githubusercontent.com/18576031/162882302-0b88f5b2-9dfd-4501-bbec-a6d2a0eef81d.png)
我电脑貌似是今天早上更新了一波app
其中包括nanazip preview
我是打开一个安装包的时候卡住了，又安装了正式版和winrar试了下，都没有问题
等我卸载了预览版本，再准备重新试试的时候发现商店已经搜不到了。。。 尴尬

**Comment by 1human** [comment]
> 看起来你系统用的英文，然后 NanaZip 语言设置的是中文吗（也许关于你反馈的问题我可能会有些灵感）
> 
> 毛利
两个都是英文，我觉得是最近更新的问题，前几天用还是好的（至少上周六，那天下载了刷机包 刷机来着）

**Comment by MouriNaruto** [comment]
我尝试复现了相关问题并试着做了修复。

https://github.com/M2Team/NanaZip/commit/64371daedaaa04a8bcb1ac5e682360408073e146

毛利

**Comment by MouriNaruto** [comment]
试图修复问题的新版本已发布 https://github.com/M2Team/NanaZip/releases/tag/1.2-Preview4

毛利

**Comment by 1human** [comment]
nice 好了！！！

Kenji Mouri ***@***.***> 於 2022年4月13日週三 下午11:45寫道：

**Comment by 1human** [comment]
> 试图修复问题的新版本已发布 https://github.com/M2Team/NanaZip/releases/tag/1.2-Preview4
> 
> 毛利

Nice   好了！！！
