### ISSUE TITLE
Latest preview crashes when opening zip files

### ISSUE THREAD

**Issue by maicol07** [M2Team/NanaZip#140]
The app simply crashing when opening zip files, either via the embedded file browser or double click from Windows file explorer. Extraction from context menu works fine

**Comment by MouriNaruto** [comment]
I need to try to reproduce the issue.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have reproduced the issue and tried to fix it.

https://github.com/M2Team/NanaZip/commit/64371daedaaa04a8bcb1ac5e682360408073e146

Kenji Mouri

**Comment by MouriNaruto** [comment]
I think you can try https://github.com/M2Team/NanaZip/releases/tag/1.2-Preview4. Hope the issue is fixed.

Kenji Mouri
