### ISSUE TITLE
点击右键菜单选项后弹出的窗口出现在底层

### ISSUE THREAD

**Issue by linchenqian** [M2Team/NanaZip#143]
用的是Win10系统。
无论是点击 “添加压缩包...” 还是 Hash，弹出的对话框总是隐藏在所有窗口的后面。不知道是不是只有我遇到这样的情形？

我认为正确的行为应该是弹出的对话框处于最顶层并作为活动中的窗口(Active Window)

感谢开发这么棒的工具，我今天才刚用上。总算是有既美观又轻便还能集成到系统的压缩工具了

**Comment by SakuraNeko** [comment]
@linchenqian ：
你好，该情况已经被确认，且属于已知问题。
我们经过排查认为此问题存在于Windows系统，我们正在跟踪微软对这类型的问题的修复情况。
一旦有进展我们会立即修复这一问题。

SakuraNeko

**Comment by MouriNaruto** [comment]
这个算是已知问题，最近算是发现了可能的解决方案

然而方法比较麻烦，现阶段需要进行构思妥善的方式

毛利

**Comment by MouriNaruto** [comment]
之前已经有人提及该问题，请参阅 https://github.com/M2Team/NanaZip/issues/86

毛利
