### ISSUE TITLE
[Feature Request] I suggest Smart Extract

### ISSUE THREAD

**Issue by NightmareWyrm** [M2Team/NanaZip#146]
It will be useful to implement this functionality similar to Bandizip's implementation:
https://en.bandisoft.com/bandizip/help/auto_dest/

And be given the option to be the default behavior when double clicking the zip file.

Thanks.

**Comment by MouriNaruto** [comment]
Duplicated, please refer to https://github.com/M2Team/NanaZip/discussions/43.

Kenji Mouri
