### ISSUE TITLE
Crash when trying to show context menu in Everything

### ISSUE THREAD

**Issue by startkkkkkk** [M2Team/NanaZip#147]
When searching things using Everything, it consistently crashes whenever the mouse gets over the context menu item of nanazip. Others in the context menu work just fine.
Appreciate it if anyone could look into this!

I use NanaZip 1.1 (1.1.194.0) from MS Store.

**Comment by MouriNaruto** [comment]
Duplicated, please refer to https://github.com/M2Team/NanaZip/issues/113

Kenji Mouri
