### ISSUE TITLE
bug反馈，Everything内右键菜单导致Everything意外退出

### ISSUE THREAD

**Issue by bfgxp** [M2Team/NanaZip#149]
测试环境Win11.22000.613   x64
在Everything内右击某个文件弹出右键菜单后，当鼠标划过nanazip时，Everything被卡退

**Comment by MouriNaruto** [comment]
看起来，Everything 可能不支持进程外的 Shell 扩展。但是由桌面桥打包的应用程序的外壳扩展需要在进程外运行。

而名为 Files 的应用程序支持 NanaZip：https://github.com/M2Team/NanaZip/issues/2。也许你应该把你的建议反馈给 Everything 的开发团队。

其实这个问题之前已经有人反馈过了：https://github.com/M2Team/NanaZip/issues/113

毛利
