### ISSUE TITLE
What do you think about the new icon design of NanaZip?

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NanaZip#15]
**Note : Now, you can head over to #17  to explore our new logo!**

![NanaZipNewIcon](https://user-images.githubusercontent.com/10867563/136609887-90ef6422-78d3-45d7-9425-9a2b65fc044d.jpg)

What do you think about it?

Kenji Mouri

**Comment by bitsper2nd** [comment]
What is it supposed to represent? I know that Nanazip is a 7zip fork, but what does it mean? I don't see it as a zip. All I see is a CD disk. I suggest you share the issue on Reddit to get more feedback. This is just my interpretation. Another might write something else.

**Comment by RGarrido03** [comment]
Hi! I got inspired by your icon, and so I created a Fluent one. In my opinion, this Fluent icon helps to keep consistency among the different Windows 11 apps.

This _logo concept_ is still rough, so some things can be changed. If you want, I can attach my Adobe Illustrator project or send this logo in other formats, such as SVG.

Feel free to give me some feedback, thanks!

| Transparent | White background |
| ----------- | ----- |
| ![NanaZip_transparent-01](https://user-images.githubusercontent.com/57329376/136638896-7e6809f3-f150-4e67-84ea-63468a1fe77d.png) | ![NanaZip_white-01](https://user-images.githubusercontent.com/57329376/136638903-b088a1d4-4769-4b87-a349-73ce5e06014d.png) |

**Comment by SakuraNeko** [comment]
I think we need some explanation about the design of the logo：

- The yellow rectangular part of the LOGO, the meaning is named notebook or file directory.
- The disc on the LOGO indicates that this software can read compressed files in many different formats.
- The strip on the right side of the LOGO is a Microsoft band (a wearable device launched by Microsoft), which implies a zipper that can be adjusted for tightness, illustrating the property that this software is compression software.
- Its overall composition indicates that the user can use compression and nested compression in various supported formats in this software.
- The dog icon on the surface of the CD-ROM has a private meaning of the author's  (@MouriNaruto)  own name for the software (which is not publicly available), and it is also a lowercase form of the letter N. The color code used for the icon is also used for this reason.

-----

We look forward to more discussions about the logo design.

Sakura Neko

October 9, 2021

**Comment by SakuraNeko** [comment]
@RGarrido03 :
Thank you very much for seeing your new design.
Your design has inspired us a lot. We will possibly use your design as part of our logo system (this will still take some time to discuss). We will update our progress here as soon as the discussion comes to fruition.

We look forward to hearing from you in the future.

Sakura Neko

October 9, 2021

**Comment by MouriNaruto** [comment]
@RGarrido03 

I think your design is very suitable for file type icons and we need some modifications based on yours.

I will change the NanaZip license to mention the all designers who are participated in. So I will mention you in the license.

Thank you very much.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I also think the new design had been inspired by the suggestion in https://github.com/M2Team/NanaZip/issues/9.

So I will also mention @lychichem in the NanaZip license.

Kenji Mouri

**Comment by wangwenx190** [comment]
win11的图标都是横向的矩形吧？你这个竖起来了，看起来怪怪的

**Comment by wangwenx190** [comment]
而且中间放张光盘，也确实有点突兀

**Comment by SakuraNeko** [comment]
@wangwenx190：

感谢你的建议。

虽然微软在实现符合流畅设计体系（Fluent Design System）的图标时，相对倾向于使用在视觉上处于横向的设计，但大多数该风格的图标是以矩形形状为主。我个人认为微软的设计可能趋向于让应用图标在用户看起来“稳定”这一原则。

我们并非是一个由微软设计和构建的应用，可能并不会完全采取和微软一致的设计路线（这同时有一定的避嫌因素）。我们会在遵循流畅设计体系（Fluent Design System）的同时确保自己的设计具有一定的独特性。

关于在应用中使用光盘元素的理由，你可以参见我在前文的发言： 

> 光碟形状的LOGO元素，表明我们的软件可以支持很多的文件格式。

希望你能继续在LOGO的设计问题上和我们讨论。

-----

【以下的英语部分是为确保其他参与本问答的建议者能加入讨论而作】

Thank you for your suggestion.

Although Microsoft has a tendency to use visually horizontal designs when implementing icons that conform to the Fluent Design System, most icons in that style are predominantly rectangular in shape. I personally think that Microsoft's design may tend to be based on the principle of making application icons look "stable" to users.

We are not a Microsoft-designed and built application, and may not follow the same design path as Microsoft (there is also a certain element of suspicion avoidance). We will follow the Fluent Design System while ensuring that our designs are unique.

For more information on the reasons for using CD-ROM elements in the application, you can see my previous statement at. 

> The disc on the LOGO indicates that this software can read compressed files in many different formats.

I hope you will continue to discuss with us on the design of the logo.

Sakura Neko

October 9, 2021

**Comment by Void48** [comment]
Please don't rush icon design. First look is important 👍🏻

**Comment by BoxterMaiti** [comment]
I also sent these to you via email, but ill just put them here as well for good measure :)
Just made these icons for fun. Think they could be pretty cool

![Concept 1 TRANSPARENT](https://user-images.githubusercontent.com/31987004/136696529-1d2c2f2f-2bc4-4a44-a02c-0a9dd5e90c33.png)
![Concept 2 TRANSPARENT](https://user-images.githubusercontent.com/31987004/136696530-85e752f1-1672-4117-9db8-c4dbbed0771e.png)

**Comment by SakuraNeko** [comment]
Hey, everybody!

First of all, thanks for all your help!

We've updated my logo designs and they are now in #17 .

I'll archive them here and you can head over there to discuss our new designs.

Looking forward to your continued participation!

Sakura Neko

October 13, 2021
