### ISSUE TITLE
[FEATURE REQUEST] - Automatically open folder that archive was extracted to

### ISSUE THREAD

**Issue by warrengalyen** [M2Team/NanaZip#151]
Add "Open Folder After Extract" checkbox option to Copy dialog. This is a feature I sorely miss from IZarc and it's still missing from 7-zip. This saves a lot of time when extracting a bunch of archives as the user doesn't have to search for and manually open the extracted folder when using the GUI.

**Comment by MouriNaruto** [comment]
Please read the roadmap.

https://github.com/M2Team/NanaZip#development-roadmap

`Try to add an option when extracting an archive to open the folder where you extracted the files, like WinRAR. (Suggested by maicol07.)`

Kenji Mouri

**Comment by warrengalyen** [comment]
Sorry, overlooked that item.
