### ISSUE TITLE
Broken SFX file

### ISSUE THREAD

**Issue by Merowinger86** [M2Team/NanaZip#153]
Hello!

I get this message when I try to execute an SFX file made with NanaZip. I've used the final version.
With the preview version it works without problems.

![Unbenannt](https://user-images.githubusercontent.com/104984893/166913182-82d2f4eb-f002-424c-8a69-fab4e48933f7.png)

It says something about an missing ordinal number (this is probably not the fitting translation) 345 in a DLL file.

**Comment by MouriNaruto** [comment]
Known issue: https://github.com/M2Team/NanaZip/issues/126

Please wait for me to update the new stable version.\

Kenji Mouri

**Comment by Merowinger86** [comment]
Ok, thank you very much! I will switch to the Preview until then.

**Comment by MouriNaruto** [comment]
NanaZip 1.2 Stable has been released. So, the issue should be resolved, and the issue will be closed.

https://github.com/M2Team/NanaZip/releases/tag/1.2

Kenji Mouri
