### ISSUE TITLE
[Feature Request]希望退出类似peazip关联不同格式的png/ico

### ISSUE THREAD

**Issue by dylumian** [M2Team/NanaZip#154]
希望退出类似peazip关联不同格式的png/ico
![Snipaste_2022-05-11_12-46-32](https://user-images.githubusercontent.com/37278466/167771067-ad7882a2-bd38-4bb0-bf03-118678d7c99a.png)

**Comment by MouriNaruto** [comment]
之前已经有人提及该问题，请参阅 https://github.com/M2Team/NanaZip/issues/142

毛利
