### ISSUE TITLE
Is the installer program compatible with Windows 10 LTSC ?

### ISSUE THREAD

**Issue by angryLid** [M2Team/NanaZip#157]
My OS version is Windows 10 LTSC 19044.1706
It seems that *.msixbundle file cannot be executed. 
![00@ @GEO~{I5OIJ}RHG$W31](https://user-images.githubusercontent.com/31571456/172058167-53ad1f7c-769c-4eda-9fee-2716c89dc5b1.png)

**Comment by MouriNaruto** [comment]
You need to use command line to install NanaZip if your OS SKU is LTSC because LTSC don't provide App Installer GUI.

Kenji Mouri
