### ISSUE TITLE
Notice of the Everything app crashing when showing NanaZip's shell extension

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NanaZip#161]
I finally found Everything will get the title of root IExplorerCommand item (or the top item show in the context menu) for several times. (Due to the design of IExplorerCommand interface and feature requirement of NanaZip. NanaZip's shell extension needs to initialize when the caller gets the root IExplorerCommand item. So NanaZip's shell extension initialized multiple times and the iterator is invalid and cause the crash of Everything app.)

So, I added the check, and the issue is fixed. (https://github.com/M2Team/NanaZip/commit/8dd2697a8f131e1a4b061d36f8ec5f2e530e30ec)

Thanks to @No5972, @startkkkkkk, @SakuraNeko, @bfgxp and @riverar.

This issue won't be closed until I submit the next version to Microsoft Store.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Referenced issues

- https://github.com/M2Team/NanaZip/issues/113
- https://github.com/M2Team/NanaZip/issues/147
- https://github.com/M2Team/NanaZip/issues/149

Kenji Mouri

**Comment by MouriNaruto** [comment]
NanaZip 2.0 Preview 1 has been released.

Kenji Mouri

**Comment by fluentmoheshwar** [comment]
Since this is fixed close the issue,
