### ISSUE TITLE
7-Zip 22.0

### ISSUE THREAD

**Issue by HylianSteel** [M2Team/NanaZip#165]
[7-Zip 22.0 was released today](https://sourceforge.net/p/sevenzip/discussion/45797/thread/9c2d9061ce/) and includes new features as well as bug fixes. I figured I'd notify you about it... if you didn't know already, that is.

**Comment by MouriNaruto** [comment]
I will integrate 7-Zip 22.00 changes to NanaZip 2.0 Preview 1 which will be released around early July.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have merged changes from 7-Zip 22.00 to NanaZip main branch.

https://github.com/M2Team/NanaZip/commit/d4edf45197c3e162d94b1f37a3d495c55a0a584d

Kenji Mouri

**Comment by HylianSteel** [comment]
Heya Mouri, a minor revision was pushed out for 7-Zip that has two changes.
https://sourceforge.net/p/sevenzip/discussion/45797/thread/c43cbc5f18/

**Comment by MouriNaruto** [comment]
I have merged changes from 7-Zip 22.01 to NanaZip main branch.

https://github.com/M2Team/NanaZip/commit/b4d7230378d4409fb9a845b04f922526ee8678e5

Kenji Mouri
