### ISSUE TITLE
Win11 传统右键菜单打开压缩包或解压等操作，程序窗口不会显示在前台而是显示在后台

### ISSUE THREAD

**Issue by harlayzhou** [M2Team/NanaZip#166]
而新版右键菜单打开压缩包或解压等操作的话，程序窗口是正常显示在前台的。

**Comment by zhang-weiyu** [comment]
+1 在win10上用右键菜单也是这样的，会在后台打开

**Comment by AndromedaMelody** [comment]
- Duplicate: #86

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #86 to get further information and discuss with us there.
