### ISSUE TITLE
如果可以的话菜单的图标可以稍微小一点

### ISSUE THREAD

**Issue by NXY666** [M2Team/NanaZip#167]
![image](https://user-images.githubusercontent.com/62371554/175544590-129eaf6f-b1c9-41cf-a7a0-35343d6f2f16.png)
我觉得图标应该只比文字大一点，现在的似乎有点太大了，显得有点拥挤——而且那个图标太大会有点糊糊的~
如果可以的话可以稍微改一下，举个例子：
![image](https://user-images.githubusercontent.com/62371554/175544652-443037e5-cc6f-4f3e-a836-4598023ba879.png)

非常喜欢NanaZip，因为它处理文件实在是太太太快了~

**Comment by MouriNaruto** [comment]
NanaZip 2.0 这部分会换成 XAML CommandBar 应该能解决你提到的问题

毛利

**Comment by AndromedaMelody** [comment]
- Duplicate: #55

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #55 to get further information and discuss with us there.
