### ISSUE TITLE
A new one is coming, and we look forward to discussing the new NanaZip icon with you!

### ISSUE THREAD

**Issue by SakuraNeko** [M2Team/NanaZip#17]
Today, we want to tell you.

With your help in this matter of icon design, we have gone one step further!

First of all, please let us thank: 

- @RGarrido03 : Presented a prototype of our document logo
- @lychichem : Reference prototypes of our program icons
- @RobbyMeeker : An interesting suggestion was provided to us
- @BoxterMaiti : Provides impactful solutions of its own design

There are also friends like @bitsper2nd, @wangwenx190 and @Void48 ...... who put forward their own solutions and understanding for the design of the logo.

And finally we'd like to thank **四月天**: our logo designer, who integrated everyone's suggestions and refined the design!

-----

### Now, the new logos of NanaZip are born.

- It contains an application icon with high contrast optimization.

| Usually | High-Contrast-Themes (In Black Themes) | High-Contrast-Themes (In White Themes) |
| ------- | ------ | ------ |
| ![LOGO](https://user-images.githubusercontent.com/22462516/136997375-4515bba1-33fe-47e0-b6a1-f3c8cc97979c.jpg) | ![High-Contrast-Themes(Black) ](https://user-images.githubusercontent.com/22462516/136996943-818bc0e7-cc6e-47f1-99d7-875a4f2cf465.jpg) | ![High-Contrast-Themes(Weite) ](https://user-images.githubusercontent.com/22462516/136996976-b5b286e5-ba96-4712-8fc4-f9c76f03aa9d.jpg) |

- A logo for archived files supported by NanaZip.

![File Icon](https://user-images.githubusercontent.com/22462516/136997033-898f5786-c47d-4f47-a768-57a580a784ea.jpg)

- And a file icon dedicated to the NanaZip self-extracting format.

![Self-Extracting File Icon](https://user-images.githubusercontent.com/22462516/136996836-eeb23dd4-849e-4199-8ab8-8d8485209d92.jpg)

-----

### Here are some screenshots of the new design in our Canary version.

![NanaZip (Canary)](https://user-images.githubusercontent.com/22462516/137066785-62ead48b-bbd1-4199-bb65-a5d91f6199ba.png)

![NanaZipContextMenu (Canary)](https://user-images.githubusercontent.com/22462516/137066749-d0c6ed51-f358-433e-b388-527461a6985f.png)

![NanaZipMainWindow (Canary)](https://user-images.githubusercontent.com/22462516/137066856-7079add6-4890-46b0-8433-ea4ca6ce564b.png)

We hope you like them!

We would like to thank you all again for your help!

-----

What do you think of these designs? 

Keep joining the discussion on our logo!

Sakura Neko

October 13, 2021

**Comment by wangwenx190** [comment]
New design looks a lot better!

**Comment by RobbyMeeker** [comment]
> @nyakaspeter 
> In my point of view, NanaZip should be a lightweight application with modern and unified user experience. So I don't want to provide special icons and extended version. My creed is writing the most compact implementations by using the least syntaxes and third-party libraries.
> Kenji Mouri

Definitely agree. Personally I prefer apps that blend into the operating system it resides in.

**Comment by Marvll** [comment]
ugly

**Comment by Marvll** [comment]
<img width="563" alt="NNZ" src="https://user-images.githubusercontent.com/88202244/137264914-7d507e2a-292b-4922-b023-7c493e3d5567.png">

**Comment by MouriNaruto** [comment]
I think we should create a new issue when we will rebrand our logo in the future. So I lock this issue.

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@techeac discussed in [#125](https://github.com/M2Team/NanaZip/discussions/125)).
- For more information, please read #274. Thank you.

> ## New Default icon?
> <sup>Originally posted by **@techeac** 2022-03-17T13:48:01Z</sup>
> I find the default icon too similar to that of folders where the color scheme specifically makes things confusing to sort.
> 
> E.g.
> ![image](https://user-images.githubusercontent.com/8141692/158822494-1722b039-6260-4ef7-88f1-cbbee454959c.png)
> 
> Is there a way for me to change this?
> Regardless i'm sure other people would appreciate it (as seen from a review or two from the Microsoft store).
> 
> Thanks!
>
> > <sup>Originally posted by **@MouriNaruto** 2022-03-17T14:01:08Z</sup>
> > `Is there a way for me to change this?`
> > 
> > I think it's nice if you can design a new one for us.
> > 
> > Here is the original file type icon: https://github.com/M2Team/NanaZip/raw/master/Assets/NanaZip_HighResolution_ArchiveFile.png
> > 
> > I will note your contribution in https://github.com/M2Team/NanaZip/blob/master/Documents/People.md if you design a new one and it's good enough to use.
> > 
> > P.S. NanaZip doesn't accept the icon which is not originally designed unless you have explicit permission from the original author.
> > 
> > Kenji Mouri

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@spettoijmm , @MouriNaruto , @LegnaOS discussed in [#197](https://github.com/M2Team/NanaZip/discussions/197)).
- For more information, please read #274. Thank you.

> ## File icon update
> <sup>Originally posted by **@spettoijmm** 2022-08-08T02:22:02Z</sup>
> I tried updating the NanaZip file icon with some fluent design principles. What do you think?
> ![V1](https://user-images.githubusercontent.com/110795387/183325007-850c3585-8207-4d08-8750-b6d2ea9fb444.png)
> ![V2](https://user-images.githubusercontent.com/110795387/183325002-d8bbac0d-8600-4c7d-af55-20acbe4b9426.png)
> ![V3](https://user-images.githubusercontent.com/110795387/183325006-b6c2f5f0-59d2-49f0-a0fb-51800ed3cc55.png)
>
> ---
>
> > <sup>Originally posted by **@MouriNaruto** 2022-08-08T02:52:14Z</sup>
> > It looks good in my perspective.
> > 
> > But I think I need to know opinions from other people in the community.
> > 
> > Kenji Mouri
> >
> > > <sup>Originally posted by **@spettoijmm** 2022-08-10T20:00:55Z</sup>
> > > No problems. In the meantime, I'll see if I can do a study to update the toolbar icons this weekend (if I have time).
> >
> > > <sup>Originally posted by **@MouriNaruto** 2022-08-11T16:29:16Z</sup>
> > > It's not necessary to create new toolbar icons because I will use XAML CommandBar with Segoe MDL2 Assets icons to replace the Win32 toolbar and bitmap icons. Hope to understand this decision.
> > > 
> > > Kenji Mouri
>
> ---
>
> > <sup>Originally posted by **@LegnaOS** 2022-08-08T03:37:56Z</sup>
> > Thanks to the designer! ^_
> > ^
> > From this icon design, it can be seen that the main visual features from NanaZip are kept intact, and the third icon is more relevant from the analysis of conforming to the characteristics of Zip files, but the lock-type icon will mistakenly think that the file has been encrypted, and it is recommended to adjust it to zipper lock. The lower left corner can be reserved empty space for different version releases such as Preview and Edge to mark well.
> > 
> > Because most of the Explorer display for small icons (such as 16 * 16 ~ 48 * 48), not HD original size icons (such as 128 * 128, 512 * 512), can be appropriate for small icons to improve its recognition
> >
> > > <sup>Originally posted by **@spettoijmm** 2022-08-10T19:56:49Z</sup>
> > > Thanks for the advice and tips on how to improve. I will edit and then post an updated version.
>
> ---
>
> > <sup>Originally posted by **@spettoijmm** 2022-08-13T20:29:17Z</sup>
> > Following @LegnaOS tips, I made new versions of the icons, now with a Zipper lock. I'm also posting my idea for the preview versions
> > 
> > ![V4](https://user-images.githubusercontent.com/110795387/184509746-6eeeb315-9c98-4f48-8ab2-4bfd35cef960.png)
> > ![V5](https://user-images.githubusercontent.com/110795387/184509747-f850d1ca-e88e-4ec3-8863-0a0e5b12988e.png)
> > ![V6 Preview](https://user-images.githubusercontent.com/110795387/184509749-031390f7-1a9e-445a-a038-ba3aec257fbe.png)
> > ![V7 Preview](https://user-images.githubusercontent.com/110795387/184509743-4ec4d376-294a-43ba-b3e2-7bff9166f6c0.png)
