### ISSUE TITLE
添加语言编码快捷切换功能，比如big5编码的zip压缩包在gb环境下乱码

### ISSUE THREAD

**Issue by 233lol** [M2Team/NanaZip#172]
添加语言编码快捷切换功能，比如big5编码的zip压缩包在gb环境下乱码。

**Comment by MouriNaruto** [comment]
其实这点已经在开发路线图的 3.x 系列计划上了

毛利

**Comment by AndromedaMelody** [comment]
- Duplicate: #70

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #70 to get further information and discuss with us there.
