### ISSUE TITLE
添加拖拽解压缩功能，像bandzip一样鼠标拖拽直接解压到目标目录，不用缓存到临时文件夹然后再移动

### ISSUE THREAD

**Issue by 233lol** [M2Team/NanaZip#173]
添加拖拽解压缩功能，像bandzip一样鼠标拖拽直接解压到目标目录，不用缓存到临时文件夹然后再移动

**Comment by MouriNaruto** [comment]
这点其实已经有人提过了，在积压的 Issue 和 Discussion 里面可以找到

毛利

**Comment by hosxy** [comment]
> 这点其实已经有人提过了（[https://github.com/M2Team/NanaZip/issues/36）](https://github.com/M2Team/NanaZip/issues/36%EF%BC%89)
> 
> 毛利

winscp 好像有这个实现，并有解释是怎么做到的 ：https://winscp.net/eng/docs/dragext

**Comment by AndromedaMelody** [comment]
- Duplicate: #36

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #36 to get further information and discuss with us there.
