### ISSUE TITLE
[Feature Request] Make NanaZip associated with HFSX

### ISSUE THREAD

**Issue by AndromedaMelody** [M2Team/NanaZip#177]
NanaZip 2.0 seems to support to open MacOS system images.

![6F957FC5284DADA69AA1A03CC67BB0AA](https://user-images.githubusercontent.com/57533055/178534651-14728fb5-a18a-43c8-81c2-f45050a731fd.png)

**Comment by MouriNaruto** [comment]
I have added it.

https://github.com/M2Team/NanaZip/commit/f3df9e0585f572672bc6ad0f22f4921a6cbb76ec

Kenji Mouri
