### ISSUE TITLE
[Feature Request] 如果压缩包内容是零散的文件（夹），解压到当前目录时自动解压到一个与压缩包同名的文件夹

### ISSUE THREAD

**Issue by wangwenx190** [M2Team/NanaZip#18]
BandiZip有一项特色功能是如果压缩包的内容是零散的文件或文件夹（也就是没有顶层目录），你选择解压到当前目录时，它会自动创建一个以压缩包文件名为名字的文件夹，来存放本该十分零散的文件，防止直接解压到外面导致当前目录的结构一下子变得十分混乱。我觉得NanaZip应该添加这个功能，用处真的很大，对用户来说会方便很多，不然每次解压之前都要先打开压缩包看一下，十分繁琐。

**Comment by SakuraNeko** [comment]
@wangwenx190 和 @SekiBetu :

我们已经知悉情况，我们会根据实际情况来决定是否添加在本议题内的功能和其位于线路图的位置（何时实现）。

这可能需要一些时间，望耐心等待。

落樱

2021年10月14日
