### ISSUE TITLE
建议-智能解压

### ISSUE THREAD

**Issue by duansheli** [M2Team/NanaZip#183]
## 功能01-智能解压 
bandizip 有个智能解压的功能 
当压缩包内，根目录下只有一个文件 
直接解压
当压缩包内，根目录下有多个文件 
则创建一个文件夹A 将压缩包解压到文件夹A中 

## 功能02-拖拽解压 
右键拖拽（压缩包、文件）到某个目录 
弹出右键菜单 
bandizip 和 360 压缩 都有这个功能

**Comment by Shomnipotence** [comment]
Agree

**Comment by huanghaobaobao** [comment]
agree

**Comment by LE7ELS** [comment]
这个功能显示排期到2025年，等得花都谢了。希望可以尽快弄好，这样就可以抛弃 BandiZip 了

**Comment by jiayiming** [comment]
建议提高智能解压优先级 目前看是2024Q3。。。真✿谢了

**Comment by hustcer** [comment]
尤其期待这个功能

**Comment by AndromedaMelody** [comment]
- 01: Duplicate #25
- 02: Duplicate #13

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #70 to get further information and discuss with us there.

**Comment by FlandiaYingman** [comment]
@duansheli @Shomnipotence @huanghaobaobao @LE7ELS @jiayiming @hustcer 
临时解决方案：https://github.com/M2Team/NanaZip/issues/25#issuecomment-1619291817
