### ISSUE TITLE
升级7-zip至22.01 (https://bit.ly/3uXOxq5)

### ISSUE THREAD

**Issue by Random-name-hi** [M2Team/NanaZip#184]
7 zip的版本已升级至22.01
升级的项目:
22.01          2022-07-15
-------------------------
- UDF support was improved to UDF version 2.60.
- HFS and APFS support was improved.
请考虑升级

**Comment by MouriNaruto** [comment]
7-Zip 22.01 的更改已经合并入 NanaZip 主分支

https://github.com/M2Team/NanaZip/commit/b4d7230378d4409fb9a845b04f922526ee8678e5

毛利
