### ISSUE TITLE
编译时资源文件出错

### ISSUE THREAD

**Issue by RayGicEFL** [M2Team/NanaZip#188]
从GitHub上clone下来，执行`./BuildAllTargets.cmd`，提示资源文件出错，例如：
```
\SevenZip\CPP\7zip\UI\Explorer\resource2.rc(5): error RC2104: undefined keyword or key name: IDS_CONTEXT_FOLDER
```
```
..\SevenZip\CPP\7zip\Bundles\SFXWin\../../UI/GUI/Extract.rc(7): error RC2104: undefined keyword or key name: IDS_MEM_ERROR
```
但很显然这些键都在头文件中定义了，资源文件也包含了对应的头文件。  

[完整输出](https://privatebin.net/?e6940c2419188831#EFDwj2Ezcuy7sSEdg6TVU7LkKC1fvcaByvAfwsdMXDyT)

**Comment by MouriNaruto** [comment]
我看编译输出也觉得挺奇怪的，于是我在自己的机器重新 clone 一份编译看看

毛利

**Comment by RayGicEFL** [comment]
使用 `Windows SDK 10.0.22000` 后解决（离大谱
