### ISSUE TITLE
[Feature Request] Allow navigation using `Alt + ←/→` or back/forward mouse button

### ISSUE THREAD

**Issue by SpecterShell** [M2Team/NanaZip#192]
Many softwares like file explorer can use `Alt + ←/→` on the keyboard and back/forward mouse button to navigate between folders. It would be nice if NanaZip can add this feature.

**Comment by xBiei** [comment]
Would love this.

**Comment by AndromedaMelody** [comment]
- Duplicate: #89

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #89 to get further information and discuss with us there.
