### ISSUE TITLE
No "NanaZip" in old style context menu on Windows 11, latest update.  

### ISSUE THREAD

**Issue by GarnetSunset** [M2Team/NanaZip#193]
![image](https://user-images.githubusercontent.com/13430434/182231388-158eedda-656d-4395-9fa1-895a400675ce.png)
Restarted explorer etc, no luck, any help? :O

**Comment by fluentmoheshwar** [comment]
Windows Version? It's fine for me.

**Comment by AndromedaMelody** [comment]
- Fix in #205 
- No new feedback for a long time, so we will close this issue. If the problem is found to appear again in Windows with the latest LCU, you can reopen(and comment) this issue or submit an issue.

Thanks for your support.

**Comment by GarnetSunset** [comment]
Sorry I didn't reply! Slipped my mind!
