### ISSUE TITLE
[Suggestion] Migrate version roadmap to Milestones via issues

### ISSUE THREAD

**Issue by hyoretsu** [M2Team/NanaZip#198]
Title. GitHub has a feature called "Milestones" which allows you to organize created issues by a label, which can be a version. The idea is that you'd create an issue for each of the features in the roadmap and add them to their milestones. When it's implemented, close them via a "closes #XXX" commit (connects a commit and an issue and automatically closes it). [Here](https://github.com/tachiyomiorg/tachiyomi/milestones)'s an example of what I'm suggesting.

**Comment by MouriNaruto** [comment]
Thank you for your suggestion. I think it's a good idea. I will try your suggestion in recent days.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Finally, I have started to use Milestones feature and will provide a central issue for discussions.

Kenji Mouri
