### ISSUE TITLE
NanaZipC help string refers to 7z

### ISSUE THREAD

**Issue by adrianghc** [M2Team/NanaZip#20]
https://github.com/M2Team/NanaZip/blob/367395890550a8a1727ad83dcd35b722b18dc811/SevenZip/CPP/7zip/UI/Console/Main.cpp#L92

This line should be updated so that the help string for the `NanaZipC` CLI executable refers to itself by its name, not 7z.

You might also want to update this line for similar reasons:

https://github.com/M2Team/NanaZip/blob/367395890550a8a1727ad83dcd35b722b18dc811/SevenZip/CPP/7zip/Bundles/SFXCon/SfxCon.cpp#L116

**Comment by MouriNaruto** [comment]
I have fixed this issue just now. You will get the fix when after I release 1.0 Preview 3.

Kenji Mouri
