### ISSUE TITLE
Why not toolbar icons use png but bmp format

### ISSUE THREAD

**Issue by emako** [M2Team/NanaZip#208]
When mouse hover those icons, background brush will make feel discomfort.

Icons in folder [https://github.com/M2Team/NanaZip/tree/main/NanaZip/Assets/Toolbar](https://github.com/M2Team/NanaZip/tree/main/NanaZip/Assets/Toolbar).

**Comment by MouriNaruto** [comment]
I will use XAML Islands CommandBar and vector font icons to remake it.

Kenji Mouri

**Comment by Shomnipotence** [comment]
you will get a new svg images or font icons library

**Comment by AndromedaMelody** [comment]
- Duplicate: #55

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #55 to get further information and discuss with us there.
