### ISSUE TITLE
Large folder - out of memory.

### ISSUE THREAD

**Issue by jennykitten78** [M2Team/NanaZip#211]
I am guessing due to Desktop Bridge file system virtualization, that while compressing a large folder (10GB) it complains about running out of memory. I have 32GB of RAM and it still says that. Switched to 7-Zip to test and it worked fine. Might be a known issue but thought I should mention it just in case.

TLDR: 10GB of DynDOLOD data from Skyrim SE (various loose meshes and textures) caused an out of memory error trying to compress to a 7z.

**Comment by michaelhachen** [comment]
Same problem here. Tried to zip a 6.8 GB File...

**Comment by dinhngtu** [comment]
This should be fixed in 2.0 Preview 2, could you try that?

**Comment by michaelhachen** [comment]
Fixed for me - thank you!

**Comment by jennykitten78** [comment]
2.0 Preview worked for me too, thank you!

**Comment by MouriNaruto** [comment]
I close this issue because this issue seemed to be fixed.

Kenji Mouri
