### ISSUE TITLE
NanaZip Icon in 2.0 Preview 2 (2.0.376.0)

### ISSUE THREAD

**Issue by SeriousHoax** [M2Team/NanaZip#212]
Hello, I see that NanaZip has changed the logo in the new Preview 2 version. The new blue logo looks beautiful. 
But on my device after updating, all archive files are showing this white icon instead of the new blue one. Is this expected or a bug?
I was looking forward to have the new blue logo.
OS: Windows 11 Stable build latest version, NanaZip Preview installed and updated from Windows Store.
![image](https://user-images.githubusercontent.com/29574622/189933418-5851a6cb-bfcd-4fdd-9098-5e8426079e29.png)

**Comment by shikkoku** [comment]
This is File type icon, Not same as application icon.

**Comment by SeriousHoax** [comment]
> This is File type icon, Not same as application icon.

I see. Is there any way to use the application icon instead?

**Comment by Shomnipotence** [comment]
> > This is File type icon, Not same as application icon.
> 
> I see. Is there any way to use the application icon instead?

https://www.winhelponline.com/blog/change-default-icon-file-type-windows/

**Comment by Wolverine1977** [comment]
Any chance the toolbar icons can be updated to the Windows 11 Colored icons rather than the B/W?
![Windows11_Icons_Color](https://user-images.githubusercontent.com/21690411/192109053-bc383d35-7bbd-4bf8-880a-d5d53f0d34be.png)

**Comment by MouriNaruto** [comment]
Close this issue since no more replies.

Kenji Mouri
