### ISSUE TITLE
Drag and Drop context menu is missing!

### ISSUE THREAD

**Issue by chmichael** [M2Team/NanaZip#214]
Hello,
  if you drag and drop with the right button the legacy context menu is missing on Windows 11. (might be on Windows 10 too)

Screenshot from 7-Zip zstd
![7zip-standard](https://user-images.githubusercontent.com/13120950/190288563-d3085dbd-8c34-42f7-a26a-67cf24dc0691.jpg)

Thank you

**Comment by MouriNaruto** [comment]
Duplicated, may be you can read https://github.com/M2Team/NanaZip/issues/13#issuecomment-974861106.

Kenji Mouri
