### ISSUE TITLE
Update Windows 11 Toolbar Images

### ISSUE THREAD

**Issue by Wolverine1977** [M2Team/NanaZip#216]
Any chance the toolbar icons can be updated to the Windows 11 Colored icons rather than the B/W?
![NannaZip Toolbar Windows 11](https://user-images.githubusercontent.com/21690411/192154717-45c61a90-258a-4058-a592-56bd81dffd32.jpg)
SVG example Images are located in: **C:\Windows\WinSxS\amd64_userexperience-core_31bf3856ad364e35_10.0.22610.1_none_19cbeffcbe79b7fb\Core\FileExplorerExtensions\Assets\images\contrast-standard**
**_theme-dark
theme-light_**
[NannaZip Example.zip](https://github.com/M2Team/NanaZip/files/9641268/NannaZip.Example.zip)
Thanks :)

**Comment by MouriNaruto** [comment]
I am worried about the Windows 11 Colored vector icon license. The B/W vector icon is Segoe series font icon and no license issue.

Kenji Mouri

**Comment by Wolverine1977** [comment]
Can we have an option to apply a custom theme? - Like 7-Zip-Theme Manager, or like WinRAR

**Comment by Shomnipotence** [comment]
> Can we have an option to apply a custom theme? - Like 7-Zip-Theme Manager, or like WinRAR

Wait for mordern UI built by XAML island

**Comment by AndromedaMelody** [comment]
- Duplicate: #55

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #55 to get further information and discuss with us there.
