### ISSUE TITLE
有没有考虑增加“快速拖放”功能？

### ISSUE THREAD

**Issue by yinghuo069** [M2Team/NanaZip#219]
习惯用拖放来解压文件夹，但是解压大文件时会出现参数错误，让我一度以为是压缩文件损坏，貌似360压缩等压缩软件也是7zip修改，但却能做到快速拖放（一步到位，不使用临时文件夹），是否考虑增加“快速拖放”功能，以提升大文件解压速度？

**Comment by AndromedaMelody** [comment]
- Duplicate: #36
- Duplicate: #173

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #36 to get further information and discuss with us there.
