### ISSUE TITLE
Thumbnails are extremely low resolution on the new version

### ISSUE THREAD

**Issue by agentmerlot1412** [M2Team/NanaZip#222]
![image](https://user-images.githubusercontent.com/58659715/193701548-aff17d74-3116-4253-9f54-949700b365eb.png)

**Comment by MouriNaruto** [comment]
The icons will continue to adjust in NanaZip 2.1.

Kenji Mouri

**Comment by MouriNaruto** [comment]
[2.0 Update 1](https://github.com/M2Team/NanaZip/releases/tag/2.0.450) fixed that. So close the issue.

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@dinhngtu ，@Shomnipotence discussed in [#197](https://github.com/M2Team/NanaZip/discussions/197)).
- For more information, please read #274. Thank you.

> <sup>Originally posted by **@dinhngtu** 2022-09-13T16:24:34Z</sup>
> I have a small feedback on the current icons: they look good at high resolutions, but at smaller sizes (e.g. File Explorer) a lot of details are missing compared to other icons, making it difficult to distinguish archive files:
> 
> ![Untitled](https://user-images.githubusercontent.com/1257909/189954765-bf0fc13b-e69b-48c9-a68c-5694612a45c5.png)
> 
> It would be good to have an icon design that is recognizable at smaller sizes, e.g. by increasing the size of the "N" logo.
>
> > <sup>Originally posted by **@Shomnipotence** 2022-09-14T00:55:25Z</sup>
> > I have known, it will be updated in the future
>
> > <sup>Originally posted by **@dinhngtu** 2022-10-05T06:15:08Z</sup>
> > I ended up making a set of small file icons myself while trying to follow the current icon design: https://github.com/dinhngtu/NanaZip/commit/7cb265e28a0f3b612b422f2e819aa21c10099565.
> > 
> > 100%:
> > ![details](https://user-images.githubusercontent.com/1257909/193992888-3c36cb1d-4c25-4646-9b97-bd80217fea33.png)
> > ![content](https://user-images.githubusercontent.com/1257909/193992871-facd3399-43c6-4a63-acae-16cf53b0d6da.png)
> > ![tiles](https://user-images.githubusercontent.com/1257909/193992890-9c114e2d-107c-4cee-8aab-b3bbfa250c94.png)
> > 
> > 150%:
> > <img width="17" alt="details" src="https://user-images.githubusercontent.com/1257909/193992923-40036084-26bc-4e07-b35b-72e6ab9400ee.png">
> > <img width="38" alt="content" src="https://user-images.githubusercontent.com/1257909/193992921-f8d3b1ca-edb8-4b01-a417-7b48f26f0079.png">
> > 
> > (you might need to open these images in Paint to see their true sizes)
