### ISSUE TITLE
“关于Nanazip”界面低对比度问题

### ISSUE THREAD

**Issue by coxine** [M2Team/NanaZip#224]
![image](https://user-images.githubusercontent.com/59347549/193756478-529ea608-0606-410b-9807-b8122f84cb1f.png)
系统深色模式，系统主题色#515C6B
下方“Github”的链接跟随系统主题色，在深色模式的黑背景下对比度只有3.09:1
建议将这个链接的颜色改为白色从而避免这个问题

**Comment by AndromedaMelody** [comment]
Thanks for your support.
This is the issue of UWP XAML. We have solved it in `Mile.Xaml` by importing `Win11's styles` form `WinUI 2.8`. NanaZip will use them starting from 2.1 development stage and changes may be seen in Late 2022.
![Screenshot 2022-10-04 163122](https://user-images.githubusercontent.com/57533055/193772894-4502b269-7f67-4c79-be2f-a7801fe0effd.png)
