### ISSUE TITLE
NanaZip Stable 2.0.396.0 启动新进程时，会附带一个名为"DesktopWindowXamlSource"的窗口

### ISSUE THREAD

**Issue by Nothing9495** [M2Team/NanaZip#225]
就像这样
并且附加的那一个窗口无法单独结束，NanaZip GUI 会随着它的结束而结束
![屏幕截图(2)](https://user-images.githubusercontent.com/90544246/193849190-1e286c60-1afa-4b8d-9afa-919ca2461d13.png)
![屏幕截图 2022-10-04 224027](https://user-images.githubusercontent.com/90544246/193849751-ad442962-601a-4b2d-ab84-9aafbc907fbd.jpg)
![屏幕截图 2022-10-04 224130](https://user-images.githubusercontent.com/90544246/193849763-0f5f7e6c-5b23-4371-a09f-08baa8c0c433.jpg)

**Comment by Nothing9495** [comment]
补充：该bug疑似仅在windows10上出现。我主力机的Win11 22H2更新NanaZip后没有发现这个问题。

**Comment by MouriNaruto** [comment]
该问题已经在手里的 Windows 10 虚拟机复现，也属于 XAML Islands 的已知问题，估计最近会首先在 Mile.Xaml 那边修复，然后逐渐推到 NanaZip 中

毛利

**Comment by MouriNaruto** [comment]
[2.0 Update 1](https://github.com/M2Team/NanaZip/releases/tag/2.0.450) 已修复，遂关闭 issue

毛利
