### ISSUE TITLE
Missing context menu when right-click dragging an archive file

### ISSUE THREAD

**Issue by 13xforever** [M2Team/NanaZip#226]
When you right-click > drag > release right mouse button, there should be a classic context menu for extraction options, but with new context menu integration it is completely missing.

![image](https://user-images.githubusercontent.com/36445/193920468-125a3ec4-f201-4d39-a2c9-56a2543f63ad.png)

As far as I know this is not a limitation as WinRAR has proper integration, and upstream 7-Zip has context menu for this scenario as well.

**Comment by MouriNaruto** [comment]
Closed because it's duplicated. Reference: https://github.com/M2Team/NanaZip/issues/13

Kenji Mouri
