### ISSUE TITLE
希望能增加一个解压后打开文件夹的功能，很实用

### ISSUE THREAD

**Issue by Zxxxxxl** [M2Team/NanaZip#228]
<img width="478" alt="屏幕截图 2022-10-18 203014" src="https://user-images.githubusercontent.com/45777921/196429799-a092387c-69a0-46eb-8738-fc7d653083ce.png">

**Comment by Crystal-RainSlide** [comment]
Easy 7-Zip 支持此功能，附议把 Easy 7-Zip 的主要新增功能全过一遍看看要不要加上：
- 它源码：http://www.e7z.org/easy7zip_src_0.1.6.7z
- 对应的 7-Zip 源码：https://7-zip.org/a/7z1604-src.7z

**Comment by Achuan-2** [comment]
+1

**Comment by AndromedaMelody** [comment]
- Duplicate: #44

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #44 to get further information and discuss with us there.
