### ISSUE TITLE
希望对ui做一些调整

### ISSUE THREAD

**Issue by qwer130140190** [M2Team/NanaZip#233]
![屏幕截图 2022-10-29 115102](https://user-images.githubusercontent.com/29937512/198812594-3e2a8bc0-07fe-4add-a34f-50bc384d7fec.png)
希望能优化一下图标和设置中的字体渲染，现在效果很不好

**Comment by qwer130140190** [comment]
设置中的字体大小很小，我是3.2k屏幕 15寸
另外看起来也怪怪的

**Comment by MouriNaruto** [comment]
看起来你用了 mactype，系统默认情况下应该是没有问题的

毛利

**Comment by qwer130140190** [comment]
> 看起来你用了 mactype，系统默认情况下应该是没有问题的
> 
> 毛利

没有使用mactype，把雅黑换成了MiSans

**Comment by AndromedaMelody** [comment]
- Duplicate: #5 

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #5 to get further information and discuss with us there.

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Modernizing UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
