### ISSUE TITLE
文件图标优化

### ISSUE THREAD

**Issue by Achuan-2** [M2Team/NanaZip#239]
从微软商店下载的nanazip，软件简洁好用，非常赞！

使用后发现唯一不满意的就是压缩包的文件图标太不明显了
nanazip的应用图标是蓝底的
![image](https://user-images.githubusercontent.com/60436214/202128384-e306d02c-7bcf-4aaa-92fb-2cd36edc8bf4.png)
而压缩文件图标却是白底的，
![image](https://user-images.githubusercontent.com/60436214/202128444-418c1923-ca9c-4a82-93d8-d2d1aac9118f.png)
个人觉得压缩文件图标蓝底的更符合大众使用习惯

**Comment by Shomnipotence** [comment]
【设计师回复】使用白色图标是为了保证与 Windows （或其他微软产品）图标设计的一致性。

文件应用图标的蓝色拉链与应用主图标相互呼应

**Comment by Achuan-2** [comment]
![image](https://user-images.githubusercontent.com/60436214/202177143-60fafe56-a808-40f9-b8a7-7a52ad595361.png)
那我建议像把拉链调大一些，现在这个太小很不明显，可以参考PPT文件图标

**Comment by Achuan-2** [comment]
@Shomnipotence 好的，期待

**Comment by MouriNaruto** [comment]
请更新 [2.0 Update 1](https://github.com/M2Team/NanaZip/releases/tag/2.0.450),然后使用系统自带的磁盘清理清理下缩略图缓存，应该解决了你的问题

遂本 issue 设为关闭状态

毛利
