### ISSUE TITLE
希望增加多语言编码切换的功能

### ISSUE THREAD

**Issue by 2858064995** [M2Team/NanaZip#240]
这项功能是我离不开bandzip和360zip的主要原因，因为经常接触一些日文系统打包的压缩包，在中文操作系统环境下就很容易变成乱码，有的时候在二次打包分享的情况下需要手动选择编码，希望可以增加一个语言编码转换的选项

**Comment by MouriNaruto** [comment]
这个建议很多人提过了，我很早就记录在 roadmap 里面

毛利

**Comment by AndromedaMelody** [comment]
- Duplicate: #70

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #70 to get further information and discuss with us there.
