### ISSUE TITLE
Crash at windows 11 with enterprise version 22H2

### ISSUE THREAD

**Issue by smionli** [M2Team/NanaZip#241]
if I open nanazip, it will always crash and dump the file and upload in here.

Can you check what happens and how to solve it?

Btw, if I use context menu to add to archive which it works but if I use open with nanazip it will crash always.

[NanaZip.ex(1).4788.zip](https://github.com/M2Team/NanaZip/files/10053559/NanaZip.ex.1.4788.zip)

**Comment by MouriNaruto** [comment]
[2.0 Update 1](https://github.com/M2Team/NanaZip/releases/tag/2.0.450) fixed that. So close the issue.

Kenji Mouri
