### ISSUE TITLE
About NanaZip Text goes beyond borders

### ISSUE THREAD

**Issue by MenschenToaster** [M2Team/NanaZip#246]
Whats the issue?
In german the about text continues after the window border.

Whats the expected outcome?
It should automatically reorder the text to continue in the next line

![grafik](https://user-images.githubusercontent.com/54715954/204094173-dfc3d883-2f7d-4f72-8fa4-3a2dfd6bdbfd.png)

**Comment by MouriNaruto** [comment]
It looks I should add the auto wrapping option for some TextBlock controls.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have fixed this issue just now.

https://github.com/M2Team/NanaZip/commit/6674d467f6b28fdbc362ac52ed3d64536111aac1

I think you will see the changes in the next preview and stable release.

Kenji Mouri
