### ISSUE TITLE
HASH的一个BUG

### ISSUE THREAD

**Issue by hyy-666** [M2Team/NanaZip#248]
对于tar.gz类型的文件HASH无法单独计算某个类型
微软商店直装版本
![image](https://user-images.githubusercontent.com/57535444/206166655-83568890-e9dc-45e0-985f-f737997510a8.png)

**Comment by MouriNaruto** [comment]
那个不是 bug，而是新的 HASH 选择界面还没有做（release 页面有写），因为 NanaZip 使用的 UI 库最近才成熟，于是先对关于对话框使用了

毛利

**Comment by hyy-666** [comment]
soga
