### ISSUE TITLE
macOS-like behavior

### ISSUE THREAD

**Issue by FezVrasta** [M2Team/NanaZip#249]
Do you think you could implement the macOS behavior where once you double click on an archive it automatically extracts it and deletes the original archive?

**Comment by Ariane-B** [comment]
I don't mind/care whether the original archive is kept or deleted, but I would very much like it if I could just double-click to extract to a folder. That's what I want to do with an archive 99 % of the time.

**Comment by Shomnipotence** [comment]
@MouriNaruto i love it，will you add it to roadmap？

**Comment by AndromedaMelody** [comment]
- Duplicate: #163

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #163 to get further information and discuss with us there.
