### ISSUE TITLE
Use new folder browser

### ISSUE THREAD

**Issue by reflectronic** [M2Team/NanaZip#251]
The folder browser used by 7-Zip is still the pre-Vista style dialog created by `SHBrowseForFolder`:

<img width="400" src="https://user-images.githubusercontent.com/27514983/206824954-a2c5cfca-de17-4d74-8aa5-a8876757c816.png" alt="Pre-vista style folder browser" />

[The code](https://github.com/M2Team/NanaZip/blob/b8dc18ff671c582a95ae8c4636a4d0923ac30869/SevenZip/CPP/Windows/Shell.cpp#L183) could be modernized to use the new folder browser (perhaps through [FolderPicker](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers.folderpicker?view=winrt-22621)).

**Comment by reflectronic** [comment]
Would you take a pull request that implements this?

**Comment by AndromedaMelody** [comment]
Thanks for your support.
NanaZip doesn't run in AppContainer, and a lots of users need run it as administrator. But [Windows.Storage.Pickers](https://learn.microsoft.com/en-us/uwp/api/windows.storage.pickers?view=winrt-22621) can't be used in an elevated application.
You can get more information from microsoft/terminal#8957 & microsoft/terminal#9760 .

**Comment by reflectronic** [comment]
Hm, that's unfortunate (ref: https://github.com/microsoft/WindowsAppSDK/issues/2504). But, we could just use IFileDialog instead like Windows Terminal does; the end result is almost the same either way.
