### ISSUE TITLE
run 

### ISSUE THREAD

**Issue by cx68cx** [M2Team/NanaZip#255]
我想在本地build nanaZip，运行了BuildAllTargets.cmd脚本，但是报错，能方便告诉下我错误的原因吗，谢谢。
![image](https://user-images.githubusercontent.com/26956875/207240461-39fd5e5f-7ef0-4a3d-96b6-5e2c9860d377.png)

**Comment by MouriNaruto** [comment]
Close this issue since no more replies.

Kenji Mouri
