### ISSUE TITLE
hope to add settings for hash options

### ISSUE THREAD

**Issue by RoachLin** [M2Team/NanaZip#260]
By default, there is no MD5 options in hash
I hope to let user to choose which hash to appear in the context menu
For example, if user choose CRC32, SHA-256 and MD5 in settings, then the hash options in context menu will be
"
CRC32
SHA-256
MD5
*
"

**Comment by RoachLin** [comment]
![Snipaste_2022-12-28_22-41-51](https://user-images.githubusercontent.com/33180391/209829026-8d5cac0a-db94-47f8-8954-630ea1335326.png)
希望可以在设置里自定义这里的hash算法，比如只显示CRC32、SHA-256、MD5这三个

**Comment by AndromedaMelody** [comment]
- Duplicate: #111

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #111 to get further information and discuss with us there.
