### ISSUE TITLE
Darkmode?

### ISSUE THREAD

**Issue by Pokeylooted** [M2Team/NanaZip#262]
Possible to get DarkMode for Nanazip ,or is it a feature planned? Would love to see it.

**Comment by shikkoku** [comment]
#254

**Comment by bigplayer-ai** [comment]
I have been waiting for dark mode since launch.
Can someone explain why is this taking so long?
I am willing to pay for it to fast up.

**Comment by MouriNaruto** [comment]
@bigplayer-ai 

https://github.com/M2Team/NanaZip/issues/270#issuecomment-1407978225

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- Duplicate: #8 

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #8 to get further information and discuss with us there.
