### ISSUE TITLE
Integrate context menu to the drop menu.

### ISSUE THREAD

**Issue by twoco** [M2Team/NanaZip#263]
Is it possible to add the context menu to the "drop menu" (or whatever it's called)?

I mean the menu if you do:
1. Right click and hold on your file (e.g. zip).
2. Move the mouse with the file dragging to a empty area (e.g. same folder).
3. Release the right mouse button.

A context menu appears with following entries:
- Extract... 
- Copy here 
- Move here 
- Create shortcuts here 
- Cancel 

On Windows 10 and below and sometimes in Windows 11 7-Zip appears in that context menu. I have no idea what Windows 11 does. But I did the same thing again on a zip file. Right drag and drop. The 7-Zip context menu only appeared one time. It's like Windows removed that by overriding the settings. Weird... Anyway. Do you know how to add an entry here and how this menu is called? 

The "Extract..." entry is the Windows build-in unzipper. Which is ugly and shameless slow.

Use case: Drag and drop file with right click and quickly extract it in that clean context menu.

![drop-context-menu](https://user-images.githubusercontent.com/53160891/211143407-7d11e92b-c968-4ad1-9a7c-c272ae5dbd84.png)
<sup>Not actual context menu from Windows 11. It's an image from the web and edited. Just for illustration.</sup>

**Comment by AndromedaMelody** [comment]
- Duplicate: #13

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #13 to get further information and discuss with us there.
