### ISSUE TITLE
Wrap checksum/hash in a menu folder.

### ISSUE THREAD

**Issue by twoco** [M2Team/NanaZip#265]
Currently all hash/checksum options are in the root menu. I want it, but I also want a clean menu. So it would be great if the entries are wrapped in a submenu/folder.

**Comment by MouriNaruto** [comment]
I will close this issue because this issue has been included in https://github.com/M2Team/NanaZip/issues/271.

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- Duplicate: #111

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #111 to get further information and discuss with us there.
