### ISSUE TITLE
Support for Right Click Drag and Drop

### ISSUE THREAD

**Issue by hl2guide** [M2Team/NanaZip#266]
For Windows it would be nice for NanaZip to support right click drag and drop showing a context menu.

_(WinRAR already supports this)_

Maybe there's some registry keys that need to be added for this?

**Comment by AndromedaMelody** [comment]
- Duplicate: #13

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #13 to get further information and discuss with us there.
