### ISSUE TITLE
NanaZip菜单项 在windows11 一级菜单能显示出来，具体是怎么做到的呢

### ISSUE THREAD

**Issue by 77xiaoweidong** [M2Team/NanaZip#27]
![image](https://user-images.githubusercontent.com/46697201/137886371-34926f39-41f9-4f7a-89ba-2621974b1975.png)

我仿照这里添加菜单，为什么还是显示在二级菜单呢？如何才能显示到一级菜单呢？

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@MouriNaruto , @Yu-DaeGi discussed in [#84](https://github.com/M2Team/NanaZip/discussions/84)).
- For more information, please read #274. Thank you.

> ## Share my experience of implementing context menu support for File Explorer in Windows 11
> <sup>Originally posted by **@MouriNaruto** December 26, 2021</sup>
> Here is the article for my experience of implementing the context menu support for File Explorer in Windows 11 and I hope it can give Windows desktop app developers some help.
> 
> https://mourinaruto.github.io/en/2021/12/25/Share-my-experience-of-implementing-context-menu-support-for-File-Explorer-in-Windows-11/
> 
> Kenji Mouri
>
> > <sup>Originally posted by **@Yu-DaeGi** January 11, 2022</sup>
> > I implemented the context menu using your code and the sample code provided by Windows.
> > However, there is a problem that runs normally on PCs with visual studio installed, but not on new PCs.
> > And how did you add the NanaZipShellExtension project to the NanaZipPackage?
> > On my computer, it is not added because it is dll.
> > Please reply.
> >
> > > <sup>Originally posted by **@MouriNaruto** January 12, 2022</sup>
> > > @Yu-DaeGi 
> > > https://github.com/M2Team/NanaZip/blob/7e084756f2b53379eb169167f0172fd873aeb395/NanaZipPackage/Package.appxmanifest#L508-L524
> > > 
> > > Kenji Mouri
