### ISSUE TITLE
Show history of locations previously used for extraction

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NanaZip#275]
- This comment is converted from the discussion (@Lawkss
 discussed in [#261](https://github.com/M2Team/NanaZip/discussions/261)).
- For more information, please read #274. Thank you.

> When clicking extract, the default folder in which the file resides is shown. I can choose a new dir. Everytime I want to extract something I need to re-select the dir again manually. Why is the dropdown box always empty? Would it not be beneficial to show a list of previously used dirs for extraction?
> 
> it is such a pain to always go into the folder I want copy the patch or click the ... and select the folder again.

**Comment by MouriNaruto** [comment]
This issue will be fixed after NanaZip migrate the configuration from registry to json.

Kenji Mouri

**Comment by AndromedaMelody** [comment]
duplicate: #314
