### ISSUE TITLE
"Unknown error" when trying to start Nanazip when installed using `scoop install -g nanazip`

### ISSUE THREAD

**Issue by bartvanandel** [M2Team/NanaZip#279]
After installing Nanazip globally using `scoop install -g nanazip` (must be run as admin), Nanazip fails to start. It immediately shows a popup with "Unknown error", without any further details.

Since `scoop install -g nanazip` doesn't do much more than installing Nanazip in a predefined location, my guess is that there is some kind of path problem.

I'm running Windows 10 (can't update) Version 22H2, and up-to-date scoop, which installs Nanazip 2.0.450.0, same as the current one in Windows Store. The one from Store runs fine, only the one installed using `scoop` fails.

**Comment by AndromedaMelody** [comment]
- According to the comment from Scoops' team in https://github.com/ScoopInstaller/Main/issues/4425#issuecomment-1436004192, Scoop doesn't support install MSIX Package (or register AppxManifest.xml).

- We hope you subscribe #169 to get further information about EXE Installer and discuss there.
  
  > - <sup>Original posted by @MouriNaruto in https://github.com/M2Team/NanaZip/pull/209#issuecomment-1236202127 at 2022-09-03T21:38:54Z</sup>
  > NanaZip will provide exe installer (You can see the empty reversed NanaZipInstaller project in the current stage.) after NanaZip is modernized by XAML Islands.
  > Kenji Mouri

- Workaround: WinGet can install MSIX Package. You can use WinGet/Microsoft Store to install NanaZip before NanaZipInstaller completed. Please see https://github.com/M2Team/NanaZip/issues/232#issuecomment-1304538835. Sorry.

As a result, We are sorry to close this issue. Thanks for your support and understanding.
