### ISSUE TITLE
能否考虑添加解压并删除的功能？

### ISSUE THREAD

**Issue by momentyl** [M2Team/NanaZip#283]
对于我个人而言，压缩包解压完是要删除的，所以我认为添加解压并删除的功能比较实用。或者可以自定义双击压缩包直接解压也是一个值得考虑的点，这样可以节省右键点击再选择解压。

**Comment by AndromedaMelody** [comment]
- Duplicate: #257

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #257 to get further information and discuss with us there.
