### ISSUE TITLE
希望更改一下一下应用内图标以适配Fluent UI。

### ISSUE THREAD

**Issue by ghr0621** [M2Team/NanaZip#286]
作者的软件太好了，就是进入软件内，感觉和图标不是一个时代的，也和Windows11有些不搭。

**Comment by MouriNaruto** [comment]
相关现代化工作正在进行中

毛利

**Comment by AndromedaMelody** [comment]
- Duplicate: #55

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you can subscribe #55 to get further information and discuss with us there.
