### ISSUE TITLE
Easy 7-Zip Features

### ISSUE THREAD

**Issue by Memphizzz** [M2Team/NanaZip#287]
Hi there,

first of all, thanks for all your hard work on NanaZip! It's a great tool!

I've been using Easy 7-zip (e7z.org) for a while now and there are some really nice features compared to the standard version which I think would be a very welcome addition to NanaZip users.

To me the most important changes can be found in the Extract Dialog:
![Scr](https://user-images.githubusercontent.com/4660924/224427693-79b3481d-753c-4be0-ab4f-dba0425037ed.png)

Here you can see a button called "Filename" which simply appends the files name to the extract path so a subfolder is created with that name with one click.
Additionally the "After extraction completes successfully" section is very handy:
1. "Open output folder"
2. "Delete source archive"
3. "Close 7-Zip"

Options 1 and 3 I use all the time and those are enabled/checked by default.
Option 2 is situational but still nice to have.

Any chance these might get implemented?

**Comment by Dziubek** [comment]
I mentioned these amenities in notification #247  https://github.com/m2team/nanazip/issues/247#issoucomment-1445132901

**Comment by AndromedaMelody** [comment]
- Duplicate: #247

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #247 to get further information and discuss with us there.
