### ISSUE TITLE
[feature] dark mode 

### ISSUE THREAD

**Issue by baraa272** [M2Team/NanaZip#29]
any hope for a true dark mode for nanazip ?

**Comment by MadTomT** [comment]
Hi,
I'm running 2.0.450.0

Roadmap.
2.0 (October 4, 2022)
 Start modernizing the UI with XAML Islands with the Windows 11 control style, dark and light mode support
 
 Does that mean the version I'm running should have a dark mode ? If so how do I enable it ?
 Thanks

**Comment by AndromedaMelody** [comment]
> <sup>Originally posted by **@MadTomT** Dec 20, 2022</sup>
> Roadmap. 2.0 (October 4, 2022) Start modernizing the UI with XAML Islands with the Windows 11 control style, dark and light mode support
> 
> Does that mean the version I'm running should have a dark mode ? If so how do I enable it ? Thanks

- Help/AboutPage & ContextMenu have supported dark mode. They will follow system settings to change theme automatically.
- `start` not `finish`, we will continue focus on it.
- For more information, please read #270 .

Thanks for your support.
