### ISSUE TITLE
 NanaZip does not become active or go on top after launching it via the Windows context menu for both folders and files.

### ISSUE THREAD

**Issue by bigplayer-ai** [M2Team/NanaZip#290]
Bug Summary: NanaZip does not become active or go on top after launching it via the Windows context menu for both folders and files.

Area Path: Files/Folders context menu

Build Number: NanaZip Store Version 2.0450.0

Severity: High (loss of productivity/intuition)

Steps to Reproduce:

Right-click multiple files or any folder
Cascade NanaZip
Press Add to Archive
NanaZip is behind the opened applications’ windows and does not become active.
Expected Result: NanaZip becomes the active window.

Actual Result: NanaZip is behind the opened applications’ windows and does not become active.

Attachments: 
[Video Documentation: ](https://streamable.com/whkv04) 
[https://streamable.com/whkv04](https://streamable.com/whkv04)
[Video Documentation #2:](https://drive.google.com/file/d/19FbuELapjtpDfC50Yj4S1oEiiKKcVB5T/view?usp=sharing)
[https://drive.google.com/file/d/19FbuELapjtpDfC50Yj4S1oEiiKKcVB5T/view?usp=sharing](https://drive.google.com/file/d/19FbuELapjtpDfC50Yj4S1oEiiKKcVB5T/view?usp=sharing)

**Comment by MouriNaruto** [comment]
I'm sorry. It's a known issue. Because Windows thinks NanaZip instance which is running from the context menu is background process, lol.

I will try to do some workaround for it.

Kenji Mouri

**Comment by AndromedaMelody** [comment]
- Duplicate: #86

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #86 to get further information and discuss with us there.
