### ISSUE TITLE
[Feature Request]希望能够增加直接右键文件 复制到剪贴板的功能 以及从剪贴板粘贴的功能

### ISSUE THREAD

**Issue by X-unable** [M2Team/NanaZip#291]
如题 没有这个功能 在压缩包内移动文件挺麻烦的（要先解压到别的地方 再移动到压缩包内）

**Comment by MouriNaruto** [comment]
该功能已经在 https://github.com/M2Team/NanaZip/issues/114 提到过，遂关闭此 issue

毛利
