### ISSUE TITLE
How to access page

### ISSUE THREAD

**Issue by kittenvr** [M2Team/NanaZip#293]
how do you access this page?
![image](https://user-images.githubusercontent.com/103120356/230772111-0e96ac1b-0996-4862-86e6-c9d01be89476.png)

**Comment by MouriNaruto** [comment]
This screenshot is from the XAML Islands based UI toolchain used in NanaZip, called Mile.Xaml.

Here is the repository: https://github.com/ProjectMile/Mile.Xaml
And here are the samples: https://github.com/ProjectMile/Mile.Xaml.Samples

Kenji Mouri
