### ISSUE TITLE
[BUG]当计算特征码，或者右击文件夹解压的时候，NanaZip的窗口不会跳到顶部

### ISSUE THREAD

**Issue by hyy-666** [M2Team/NanaZip#298]
RT，这种情况很影响使用，能不能在弹出窗口的时候弹到顶部？

**Comment by AndromedaMelody** [comment]
- Duplicate: #86

Thanks for your support. We are sorry to close this issue because it is duplicate.
We hope you subscribe #86 to get further information and discuss with us there.
