### ISSUE TITLE
Application icon suggestion

### ISSUE THREAD

**Issue by RobbyMeeker** [M2Team/NanaZip#3]
Great app, but frankly it is a travesty that the app icon is not a banana being unzipped... I mean for god's sake its in the name!

Something like [this, but in a 2D style](https://andyearhole.files.wordpress.com/2017/03/dandy-warhols-1.jpg?w=1305)

Just a thought, great work though!

**Comment by RobbyMeeker** [comment]
I've made a couple mockups of something that might fit better (in my opinion). 

https://imgur.com/a/0meZQuD

**Comment by MouriNaruto** [comment]
> but frankly it is a travesty that the app icon is not a banana being unzipped

This project is called `NanaZip` because the `nana` is the romaji of `なな`, means `seven` in Japanese. So they will know `NanaZip` is a `7-Zip` derivative if they know a little Japanese because this is a pun which is easy to understand.

Kenji Mouri

**Comment by RobbyMeeker** [comment]
> > but frankly it is a travesty that the app icon is not a banana being unzipped
> 
> This project is called `NanaZip` because the `nana` is the romaji of `なな`, means `seven` in Japanese. So they will know `NanaZip` is a `7-Zip` derivative if they know a little Japanese because this is a pun which is easy to understand.
> 
> I know the current icon of NanaZip is not the final icon because it still need some adjustments by the icon designer.
> 
> Kenji Mouri

Very interesting, that makes a lot more sense. Thanks for the insight there!
