### ISSUE TITLE
Has NanaZip got abandoned?

### ISSUE THREAD

**Issue by d5aqoep** [M2Team/NanaZip#308]
I see no updates since Nov 2022 and modernization of the UI date extending by more than one year. Just wondering whether I should wait for new preview build or switch to Winrar?

**Comment by MouriNaruto** [comment]
It's a duplicated issue.

You can read my answer from https://github.com/M2Team/NanaZip/issues/201.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Note: You also can get NanaZip-related development progress at [my twitter](https://twitter.com/MouriNaruto).

Kenji Mouri
