### ISSUE TITLE
Why there's no proper 3.0 version installer

### ISSUE THREAD

**Issue by megapro17** [M2Team/NanaZip#310]
I wanted to try the latest avaliable version and checked out Preview channel, but it's outdated horribly, with only 2.1 version. What's the point of creating the same two channels if none of them are providing the latest version? 
Anyway, then I tried to install appx from CI/CD, and it didn't wanted to install at all, because of lack of signing. No matter how I tried to sign it, it just doesn't want to. 
Then I ran from unpacked folder `Add-AppxPackage NanaZip\AppxManifest.xml -Register`. This time it did worked somehow, but all icons of archives are missing, they're just white. I didn't got any critical bugs for a month I'm using an app this way. So I'm wonder can you upload a signed app into github releases or update a Preview version, so finally anyone can use latest version, when Preview version is supposed to do that, but in reality it's not

**Comment by Soitora** [comment]
What crack are you smoking?

There is no 3.0 until at earliest third quarter of next year... version 2.1 is the latest available in preview.

**Comment by megapro17** [comment]
What's a point of a preview version, if it's outdated af?? Make it 3.0 version there

**Comment by Soitora** [comment]
> What's a point of a preview version, if it's outdated af?? Make it 3.0 version there

What do you mean? How is ito outdated?
Where are you seeing version 3.0? It's not released

**Comment by megapro17** [comment]
You're dumb, it's in development, preview version was made for that, for testing a new, unreleased versions

**Comment by Soitora** [comment]
> You're dumb, it's in development, preview version was made for that, for testing a new, unreleased versions

It still needs to have an actual stable enough release for that. It's called "Preview", not "Alpha"/"Canary"/etc

**Comment by megapro17** [comment]
It is stable enough, I'm using it for a 3 months and didn't got any problems, and it's much better than a stable or preview version, because there's no bug with zstd compression level

**Comment by d5aqoep** [comment]
Roadmap says next release Q3 2024. I assume that this is a dead project. 2 years for update is ridiculous. I already switched to Winrar with custome dark theme.

**Comment by modz2014** [comment]
In consideration of the primary developer's commitments and responsibilities, it is essential to acknowledge that their time and expertise are valuable resources that cannot be allocated arbitrarily without due consideration. It is imperative to understand that the developer's availability may be subject to ongoing projects and commitments. Therefore, it is advised to exercise patience while awaiting their engagement. For further updates or inquiries, you may reach out to the developer directly using their handle, @MouriNaruto. Your understanding of these factors is greatly appreciated.

**Comment by megapro17** [comment]
Chat gpt

**Comment by Soitora** [comment]
Are you happy now?
