### ISSUE TITLE
Sync upstream updates

### ISSUE THREAD

**Issue by wzwtt** [M2Team/NanaZip#311]
The [7-Zip version 23.00](https://sourceforge.net/p/sevenzip/discussion/45797/thread/713c8a8269/) had been released on 7th May. Can the core be updated to 23.00?

**Comment by MouriNaruto** [comment]
But the Igor has not released the source code until today.

Kenji Mouri

**Comment by Pinguin2001** [comment]
Stable 22.01 has been released and source is out now as well

https://sourceforge.net/projects/sevenzip/files/7-Zip/22.01/

**Comment by Pinguin2001** [comment]
https://www.7-zip.org/a/7z2301-src.7z

7-zip 23.01 source is up now! 🎉

**Comment by MouriNaruto** [comment]
@Pinguin2001 

I will synchronize to that in the recent days.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I think it's helpful for you to read this: https://github.com/M2Team/NanaZip/issues/336

Kenji Mouri.

**Comment by MouriNaruto** [comment]
Here is the new status: https://github.com/M2Team/NanaZip/issues/336#issuecomment-1722243641

Kenji Mouri

**Comment by MouriNaruto** [comment]
NanaZip 3.0 Preview 0 has been submitted to the Windows Store successfully.

https://github.com/M2Team/NanaZip/releases/tag/3.0.756

Kenji Mouri
