### ISSUE TITLE
Override codepage in UI

### ISSUE THREAD

**Issue by illeatmyhat** [M2Team/NanaZip#318]
Many people create archives encoded in SHIFT-JIS or other encodings, which when opened with the typical installation using Unicode, results in total garbage.
The solution for 7-Zip is
```powershell
 & 'C:\Program Files\7-Zip\7z.exe' -mcp=932 x .\フーバー.zip
```
which is to use the command line's manual codepage switch to change the codepage.
What needs to be changed to add this switch into the UI so that I don't have to open the terminal and remember how to do this?

**Comment by AndromedaMelody** [comment]
- duplicate: #70
