### ISSUE TITLE
Better translation files

### ISSUE THREAD

**Issue by maicol07** [M2Team/NanaZip#33]
Hi,

I don't know if it's possible due to the translation files are also used by 7zip, but can you improve the current translation files (new format)?

Currently, the txt format is difficult to handle. You can try to use VS translation file and maybe set up a project in a translation platform, such as Crowdin (it's free for open source projects)

**Comment by MouriNaruto** [comment]
NanaZip has migrated language files from .txt to .resw. (Implemented by AndromedaMelody.)
https://github.com/M2Team/NanaZip/commit/1f477fa7f062ffcd295961bc8d7f4b6dbe34055d

I closed the issue because this issue is solved.

Kenji Mouri
