### ISSUE TITLE
Feature Request: Drag-and-drop add to archive

### ISSUE THREAD

**Issue by trparky** [M2Team/NanaZip#332]
I'd like to see the ability to take a file and drag it onto an existing archive file and have NanaZip be able add that selected file to the chosen archive.

**Comment by modz2014** [comment]
it already does this

**Comment by trparky** [comment]
How? I've tried to drag-and-drop a file in Windows Explorer onto a 7ZIP file and it doesn't do anything.

**Comment by modz2014** [comment]
yes it's working fine for me

**Comment by trparky** [comment]
Are you dragging it onto the program window? Because that's not what I'm talking about.

I'm talking about taking a file that I want to add to a ZIP or 7ZIP file in Windows Explorer, drag it onto a compressed file in Windows Explorer, and then having NanaZIP open said compressed file to add the files that I dragged onto it in Windows Explorer.

**Comment by trparky** [comment]
[Steps to recreate.zip](https://github.com/M2Team/NanaZip/files/12524363/Steps.to.recreate.zip)
That's what I'm talking about, that doesn't work at all.

**Comment by modz2014** [comment]
the zip file is broken so i cant see it @trparky

**Comment by trparky** [comment]
[Steps to recreate.zip](https://github.com/M2Team/NanaZip/files/12524428/Steps.to.recreate.zip)

**Comment by modz2014** [comment]
the screens you uploading are not working for me

**Comment by modz2014** [comment]
yes but there is no screens when you are taking them

**Comment by trparky** [comment]
I believe you need to open the file in Microsoft Edge, it's made by the built-in Windows Steps Recorder so I wouldn't be surprised that you need a Microsoft program to open it.

**Comment by modz2014** [comment]
I had to open it on my other pc on windows 11 not windows 10 thats strange where is this temp folder located

**Comment by trparky** [comment]
On the desktop. I have a temp directory that I created on my desktop that junk goes into and gets cleaned on a regular basis.

**Comment by trparky** [comment]
Yes, a simple folder on my desktop called "temp".

**Comment by modz2014** [comment]
yes it seems to work fine on my end i created a folder called temp on desktop then created a random folder and then added a file into and it saved i also ziped temp folder as well

**Comment by trparky** [comment]
[Steps to recreate v2.zip](https://github.com/M2Team/NanaZip/files/12529341/Steps.to.recreate.v2.zip)
Another set of steps made by Windows 11 Steps Recorder. This time in a completely new and clean installation of Windows 11 in a Hyper-V VM. Again, this is a clean installation of Windows 11 with a fresh installation (non-preview) of NanaZIP installed.

Dragging a file onto a ZIP file seems to work, however... dragging a file onto a 7ZIP file doesn't. Again, this is a clean installation of Windows 11 so as to eliminate any possible issues that may have arisen on a system that had a previous archiving program installed on it.

**Comment by modz2014** [comment]
yer works fine for me

**Comment by trparky** [comment]
Then I don't know what's going on then. It plain doesn't work for me. Or maybe it's my own fault for not explaining what I want it to do.

**Comment by trparky** [comment]
Either way, I can't wait until Windows supports 7ZIP natively. I'm closing this ticket.
