### ISSUE TITLE
The "Longhorn Reset" of NanaZip

### ISSUE THREAD

**Issue by MouriNaruto** [M2Team/NanaZip#336]
Yesterday, I have found I met the "Longhorn Build 4093" moment in NanaZip project. And I found Mr. Igor changed a lot from 22.01 to 23.01. 7-Zip has 1200+ source code files and he changed 950+.

So, I start to do something similar to "Longhorn Reset" in NanaZip. First, I start to rewrite the core implementation based on 7-Zip 23.01. Everyone can see the progress in NanaZip.Core project in NanaZip repository.

I have done several commits and progress is so smooth than I thought before.

After I have done the 7-Zip ZS feature integration for NanaZip.Core. I will remove lots of old implementations.

Also, 7-Zip's ABI compatibility looks nice. I have replaced the 7z.dll in 7-Zip 22.01 mainline to NanaZip.Core.dll. And it's all fine. It's OK to use all extra HASH algorithms I integrated to NanaZip.Core.dll just now.

![image](https://github.com/M2Team/NanaZip/assets/10867563/872c0866-6fdf-42cd-84ba-efc2a00a88f1)

So, it may need some time to release the next preview of NanaZip. I hope I can finish this work before October.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Here is some good news.

The development work on NanaZip.Core.dll has been completed successfully. In the next version of NanaZip will use this implementation. Here are some changes from old NanaZipCore.dll to new NanaZip.Core.dll:

- Synchronize the 7-Zip mainline implementations to 23.01.
- Synchronize the 7-Zip ZS implementations to https://github.com/mcmilk/7-Zip-zstd/commit/62bfad55c339f7f76b1880a59378245b6dfbbf49.
- Add the SM3 HASH algorithms from [GmSSL](https://github.com/guanzhi/GmSSL).
- Split additional changes for 7-Zip implementations from non-7-Zip mainline in the [Extensions](https://github.com/M2Team/NanaZip/tree/main/NanaZip.Core/Extensions) folder of NanaZip.Core project.
- Synchronize Brotli implementations to v1.1.0.
- Synchronize the RHash implementation to https://github.com/rhash/RHash/commit/b8c91ea6551e99e10352386cd46ea26973bb4a4d.

In addition to

**Comment by MouriNaruto** [comment]
The Self Extracting Executable part has been applied to some of these changes successfully. So, NanaZip had synchronized the 7-Zip mainline implementations to 23.01.

Kenji Mouri

**Comment by MouriNaruto** [comment]
NanaZip 3.0 Preview 0 has been submitted to the Windows Store successfully.

https://github.com/M2Team/NanaZip/releases/tag/3.0.756

Kenji Mouri

**Comment by Eldenroot** [comment]
When new release: )

**Comment by dcog989** [comment]
> When new release: )

[The planned late December release is not happening. No ETA.](https://github.com/M2Team/NanaZip/issues/347#issuecomment-1868202497)
