### ISSUE TITLE
Will NanaZip be coming to chocolately?

### ISSUE THREAD

**Issue by slrgt** [M2Team/NanaZip#337]
Chocolately is a great way to install programs from the terminal and a great way to have them auto update. Will NanaZip be coming to chocolately? 

Here is the website in case you haven't used it https://chocolatey.org/

**Comment by MouriNaruto** [comment]
It looks like chocolatey already has the NanaZip package.

https://community.chocolatey.org/packages/nanazip

Kenji Mouri

**Comment by eggbean** [comment]
I use scoop instead of chocolately, but they similar. However, I prefer to use scoop only for command line programs and I use WinGet for Windows desktop software.

There are four Nanazip packages available on Winget - Stable and Preview and Win32 and Microsoft Store versions.

```
F:\Users\jason\>winget search nanazip
Name            Id                     Version   Match            Source
-------------------------------------------------------------------------
NanaZip         9N8G7TSCL18R           Unknown                    msstore
NanaZip Preview 9NZL0LRP1BNL           Unknown                    msstore
NanaZip         M2Team.NanaZip         2.0.450.0                  winget
NanaZip Preview M2Team.NanaZip.Preview 3.0.756.0 Command: nanazip winget

```
