### ISSUE TITLE
在特定目录操作时文件被重定向

### ISSUE THREAD

**Issue by TWEril** [M2Team/NanaZip#34]
当我在`%AppData%`这个目录里执行压缩或解压操作时
文件会被重定向至此位置
`C:\Users\%UserName%\AppData\Local\Packages\40174MouriNaruto.NanaZip_gnj4mf6z9tkrc\LocalCache\Roaming\`

系统：Windows 11，22000.282
NanaZip：1.0 Preview 3 (x64)

**Comment by oxygen-dioxide** [comment]
> 当我在`%AppData%`这个目录里执行压缩或解压操作时 文件会被重定向至此位置 `C:\Users\%UserName%\AppData\Local\Packages\40174MouriNaruto.NanaZip_gnj4mf6z9tkrc\LocalCache\Roaming\`
> 
> 系统：Windows 11，22000.282 NanaZip：1.0 Preview 3 (x64)

绿色版运行就不会重定向了
方法：安装包后缀名改为zip，解压，里面如果还有安装包就继续解压，直到出现exe为止，运行NanaZip.exe。

**Comment by MouriNaruto** [comment]
@oxygen-dioxide 

虽然当前版本可以这样做，但不保证以后的版本可以这样做，随着现代化进度的加深
对于 unpackaged 模式，看起来巨硬貌似都没怎么玩明白，所以我对此表示观望一到两年再看

**Comment by MouriNaruto** [comment]
@TWEril @oxygen-dioxide 我尝试修复了一下问题，最近应该会试着上传包到微软商店，如果能通过审核就算修复成功。

https://github.com/M2Team/NanaZip/commit/6fd19b70292273b7b32e68c656d18c3f01c7ce7c

毛利

**Comment by MouriNaruto** [comment]
NanaZip 1.0 Preview 4 发布了，从 Preview 4 开始在商店提供 NanaZip Preview 应用方便测试。

由于微软审核限制（特意发我邮件表示不支持这样做），于是我换了另一种方式解决该问题，但有如下限制：

- 在 `%UserProfile%\AppData` 目录中除 `Local`, `LocalLow` 和 `Roaming` 之外的目录操作依然会被重定向，但个人感觉排除这三个目录后应该能让解决大部分人遇到的情况。
- 该方式只有 Windows 11 支持。

毛利

**Comment by vvb2060** [comment]
https://learn.microsoft.com/en-us/windows/uwp/packaging/app-capability-declarations#restricted-capabilities
> The unvirtualizedResources restricted capability enables your application to declare the [RegistryWriteVirtualization](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-registrywritevirtualization) and [FileSystemWriteVirtualization](https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-desktop6-filesystemwritevirtualization) elements in its package manifest to disable virtualization for the registry and file system. These declarations prevent the system from virtualizing any writes to HKEY_CURRENT_USER or to the user's AppData folder, respectively. This is useful in scenarios where your application expects other applications to read or write the same registry or file system entries as your application.

由于缺乏权限，因此排除声明是无效的，现在的行为就是[文档](https://learn.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-behind-the-scenes)里面的预期行为

| Operation | Result | Example |
| --- | --- | --- |
| Read or enumerate a well-known Windows file or folder | A dynamic merge of `C:\Program Files\<package_full_name>\VFS\<well_known_folder>` with the local system counterpart. | Reading `C:\Windows\System32` returns the contents of `C:\Windows\System32` plus the contents of `C:\Program Files\WindowsApps\<package_full_name>\VFS\SystemX86`. |
| Write under `AppData` | **Windows 10, version 1903 and later**: New files and folders created under the following directories are redirected to a per-user, per-package private location:<ul><li>Local</li><li>Local\Microsoft</li><li>Roaming</li><li>Roaming\Microsoft</li><li>Roaming\Microsoft\Windows\Start Menu\Programs</li></ul>In response to a file open command, the OS will open the file from the per-user, per-package location first. If that location doesn't exist, then the OS will attempt to open the file from the real `AppData` location. If the file is opened from the real `AppData` location, then no virtualization for that file occurs. File deletes under `AppData` are allowed if user has permissions.<p/><p/>**Earlier than Windows 10, version 1903**: Copy on write to a per-user, per-app location. | `AppData` is typically `C:\Users\<user_name>\AppData`. |
| Write inside the package | Not allowed. The package is read-only. | Writes under `C:\Program Files\WindowsApps\<package_full_name>` aren't allowed. |
| Write outside the package | Allowed if the user has permissions. | A write to `C:\Windows\System32\foo.dll` is allowed if the package doesn't contain `C:\Program Files\WindowsApps\<package_full_name>\VFS\SystemX86\foo.dll`, and the user has permissions. |

**Comment by vvb2060** [comment]
> 对于 unpackaged 模式，看起来巨硬貌似都没怎么玩明白，所以我对此表示观望一到两年再看

现在是packagedClassicApp模式呀，不是win32App模式。文档说 Executable, EntryPoint="windows.fullTrustApplication" (equivalent to uap10:RuntimeBehavior="packagedClassicApp", uap10:TrustLevel="mediumIL")
虽然文档说AppContainer信任级别才有文件系统虚拟化，好像在暗示mediumIL没有，但不测试不清楚是不是如此。
由于已经 MinVersion="10.0.19041.0" 所以可以用uap10。

https://learn.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-application
