### ISSUE TITLE
希望有深色模式

### ISSUE THREAD

**Issue by ghost** [M2Team/NanaZip#343]
希望能自动根据系统切换颜色模式

**Comment by MouriNaruto** [comment]
该特性已经在开发了

毛利

**Comment by RichardZhang4** [comment]
目前还没看到😂

**Comment by MouriNaruto** [comment]
（在做了系列）

暗黑模式的一些实现会放在 https://github.com/M2Team/NanaZip/tree/main/NanaZip.Frieren 这边，还在填坑中

毛利

**Comment by MouriNaruto** [comment]
![image](https://github.com/M2Team/NanaZip/assets/10867563/9b6ea478-1a56-46ef-be66-a04cfa2cb85f)

暗黑模式填坑事务基本结束，效果应该看起来不错

毛利
