### ISSUE TITLE
fatal error, RC1015: cannot open include file 'windows.h'

### ISSUE THREAD

**Issue by uhuntu** [M2Team/NanaZip#344]
![image](https://github.com/M2Team/NanaZip/assets/4939569/bb8d5d7c-ad2d-4ea4-b577-7478c7460e2a)

**Comment by uhuntu** [comment]
Hi there, I am new in NanaZip, I would like to play around something about it, which tool I am using is Visual Studio 2022, in most cases if I like to modify resources, I will switch to "Resource View" to visually see what for example Dialog looks like etc.

But for NanaZip, I am feeling frustrated even I open any rc files, it will pop up the error dialog with error message "fatal error, RC1015: cannot open include file 'windows.h'".

Does anyone know how it is happening ?

**Comment by MouriNaruto** [comment]
There are many Win32 resource files in NanaZip project which is not support editing via Visual Studio IDE GUI.

Kenji Mouri
