### ISSUE TITLE
拖拽文件至文件夹，直接解压至目标文件夹，不使用 Temp 作为中转

### ISSUE THREAD

**Issue by Puqns67** [M2Team/NanaZip#36]
如标题，相关的我也没怎么了解过，如果 Windows 无法获取目标文件夹或因其他原因无法做到，Close 即可。

**Comment by MouriNaruto** [comment]
因为 Windows Shell API 在此操作下无法获取目标文件夹，最多只能做到把 Shell 文件操作窗口隐藏（NanaZip 2.x 阶段重构界面时会尝试）。

毛利

**Comment by hosxy** [comment]
Bandizip 有这个功能，不知道是怎么实现的
![图片](https://user-images.githubusercontent.com/17108640/145378685-a1a13b37-7e00-40c8-a157-ace2a2ab76a9.png)

**Comment by SakuraNeko** [comment]
@hosxy ：

Bandizip 可能在实现该功能时不依赖Windows Shell API或使用了未公开的方法，故我们无法保证我们能做到同等效果，但我们会在后续尝试实现。

SakuraNeko

**Comment by gszj2018** [comment]
Bandizip是使用Shell Extension实现的。另外也有开源软件WinSCP实现了类似的功能。

**Comment by gszj2018** [comment]
Bandizip是使用Shell Extension实现的。另外也有开源软件WinSCP实现了类似的功能。

需要注意的是，根据相关文档（[https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare](https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-prepare)），使用这种技术的程序可能无法通过Windows Store分发。
