### ISSUE TITLE
Open GitHub Discussions

### ISSUE THREAD

**Issue by dcog989** [M2Team/NanaZip#363]
Could we please have the GitHub Discussions opened? 

It would be beneficial for users to have somewhere to discuss things without immediately opening an Issue ticket. It would therefore reduce the number of raised / active issues?

**Comment by dcog989** [comment]
@MouriNaruto 

It seems you work alone on this project - apart from the occasional pull request. Are there any areas outside of coding that you would like assistance with? For example, have you considered opening GitHub Wiki for the project so that e.g. a user manual could be written?

**Comment by MouriNaruto** [comment]
I have tried GitHub Discussions before and I find I am suitable for that infrastructure. I think sending issues will be good.

If someone wants to contribute the user manual, I think sending a PR and putting the contents in the Documents folder will be good. In my opinion, GitHub Wiki is not a good feature for people who want to maintain both documents and source code at the same time.

Kenji Mouri

**Comment by MouriNaruto** [comment]
> Are there any areas outside of coding that you would like assistance with?

https://github.com/M2Team/NanaZip/issues/302 is one of examples for me need some help.

Kenji Mouri

**Comment by dcog989** [comment]
Thank you for your response and explanation on the suggestions I raised. All good.

Thank you for developing this excellent software. :)
