### ISSUE TITLE
Strange installation

### ISSUE THREAD

**Issue by henrypp** [M2Team/NanaZip#367]
I install nanazaip normally:

![sshot-001](https://github.com/M2Team/NanaZip/assets/3902025/964e2637-d988-4faa-8f7e-4cb3d4aa3846)
(or whatever doubleclick on msix)

but it is not running and not register context menu:

![sshot-002](https://github.com/M2Team/NanaZip/assets/3902025/d96720a9-269c-4d70-bbba-6acb515468a9)

not any version are running, not beta, not stable

windows latest 22635

what can i do? as i see: all required modules are in msix package, so...

**Comment by MouriNaruto** [comment]
Maybe you need to connect to the internet to make Windows automatically get AppX license from Microsoft Store.

Kenji Mouri

**Comment by henrypp** [comment]
inet exists, not any logs in FW, complete empty, i did not checks only dnscrypt, i check

**Comment by redactedscribe** [comment]
@henrypp Did you manage to fix this? I am also seeing this error and I believe it's because of my firewall.

**Comment by redactedscribe** [comment]
In my case, the answer was to allow `login.live.com` (service: `wlidsvc`) and `licensing.mp.microsoft.com` (service: `licensemanager`) through my firewall.

No more error preventing NanaZip from launching.

**Comment by MouriNaruto** [comment]
The issue is solved. Read https://github.com/M2Team/NanaZip/issues/398 for more information.

Kenji Mouri
