### ISSUE TITLE
Make installation package available outside of Microsoft Store

### ISSUE THREAD

**Issue by Kihltech** [M2Team/NanaZip#37]
Since a Microsoft Account is needed in Windows 11 to install an application from the Microsoft Store, there is no way that I know of that can be used to install NanaZip from without Microsoft Store.

**Comment by MouriNaruto** [comment]
You can download the offline msix package in GitHub Release.

https://github.com/M2Team/NanaZip/releases

Kenji Mouri

**Comment by Kihltech** [comment]
Thanks Mouri, I hadn't found that way to get the bundle.
