### ISSUE TITLE
Feature Suggestion: Icon Customization

### ISSUE THREAD

**Issue by Kytech** [M2Team/NanaZip#38]
Icon customization has been around in 7zip for quite a while with 7zip theme manager (7zTM). Since customizing 7zip icons is still fairly popular, it would be great to be able to customize the icons in NanaZip. (I for one like to make all my archive files use a theme that closely matches the system theme's default zip icon.) Adding icon customization as a built-in, first-class feature would probably draw a lot of people who like to customize over to NanaZip. It may even be possible to support 7zTM formatted themes as well, at least for icons at minimum, since their format is pretty simple and straightforward.

**Comment by MouriNaruto** [comment]
You can download the offline msix package in GitHub Release.

https://github.com/M2Team/NanaZip/releases

Kenji Mouri

**Comment by MouriNaruto** [comment]
Due to the mechanism of App Model, NanaZip is unable to implement that.

If you wonder to change icons. You need toi repack the msix package like adding Magisk to Windows Subsystem for Android.

**Comment by AndromedaMelody** [comment]
- This comment is converted from the discussion (@almightyyoda2012 , @MouriNaruto discussed in [#191](https://github.com/M2Team/NanaZip/discussions/191)).
- For more information, please read #274. Thank you.

> ## Switching icons
> <sup>Originally posted by **@almightyyoda2012** July 28, 2022</sup>
> I noticed there are alternate icons available in the 'Assets' folder, is there a way to switch nanazip to use those icons rather than the default?
>
> > <sup>Originally posted by **@MouriNaruto** July 29, 2022</sup>
> > Currently, it's only application icon and file type icon for NanaZip and NanaZip Preview in that folder.
> >
> > Kenji Mouri
