### ISSUE TITLE
Improved Windows 11 Fluent-style icons

### ISSUE THREAD

**Issue by komo1iddin** [M2Team/NanaZip#39]
There are better icons Windows 11 Fluent-style icons in deviantart. You can check it here: [Fluent 7Zip Icons by Th3Z](https://www.deviantart.com/th3z/art/Fluent-7Zip-Icons-874298467)

[What it looks like](http://www.wincore.ru/uploads/posts/2021-11/1636274893_snimok-ekrana-2021-11-07-114238.png)

They better match the Windows 11 design and greatly improve the NanaZip experience because they look just like the zip icon in Windows Explorer.

**Comment by MouriNaruto** [comment]
Mentioned in the roadmap, NanaZip 2.x development stage will rewritten the UI with XAML Islands with Windows 11 control style and Mica material. So we will use vector icons in the UI.

The application icon and file association icon will be redesigned again in NanaZip 2.x.

But we need to release 1.0 stable first. (There are lots of work to do.)

Kenji Mouri
