### ISSUE TITLE
7-Zip 24.04 Beta

### ISSUE THREAD

**Issue by PopuriAO29** [M2Team/NanaZip#397]
7-Zip 24.04 Beta was released!

https://sourceforge.net/p/sevenzip/discussion/45797/thread/b54210a186/

What's new after 24.03 Beta:

* New menu item in 7-Zip File Manager: "Tools / Delete Temporary Files...". This menu item opens a window showing temporary folders and files created by 7-Zip in the user's "Temp" folder on a Windows system. In this window, the user can delete temporary files

Like in 24.01, 24.02 and 24.03, the source code will be available later according what Igor said.

As for 24.02, the bug ISO archive couldn't open, the issue was fixed in 24.03.

Don't worry, we could wait if the source code is released soon.

**Comment by MouriNaruto** [comment]
Working on integrating the 7-Zip 24.05. Please read https://github.com/M2Team/NanaZip/issues/401.

Kenji Mouri
