### ISSUE TITLE
CLI entry point

### ISSUE THREAD

**Issue by be5invis** [M2Team/NanaZip#4]
`7-zip` has a useful CLI entry point `7z.exe` that allows users to compress/decompress files in the command line. NanaZip should support this too.

**Comment by MouriNaruto** [comment]
> NanaZip should support this too.

I always think expose execution alias of command line version (Windows subsystem version and Console subsystem version) and graphical version is necessary. So I wonder to expose NanaZip, NanaZipC and NanaZipG to user. But I have met an issue when I upload it to the dashboard.

![image](https://user-images.githubusercontent.com/10867563/135181974-e6ad71a3-cbe7-4160-9d2d-b86a598c964c.png)

I need the way to solve it but I don't know that.

Kenji Mouri

**Comment by be5invis** [comment]
From this:

https://github.com/python/cpython/blob/main/PC/store_info.txt

It looks like:

> When submitting a new app, the HeadlessAppBypass waiver will be needed.
> To request this, send an email to PartnerOps@microsoft.com with the app
> ID (12 character token available from the dashboard). The waiver needs
> to be applied *before* uploading the package (as of November 2019).

**Comment by be5invis** [comment]
Something else may help: https://stackoverflow.com/questions/63404924/how-can-i-get-my-msix-installer-to-add-my-cli-application-binary-to-the-path

**Comment by MouriNaruto** [comment]
Thank you very much. I will do that in recent days. And I will report the progress to this issue.

Kenji Mouri

**Comment by be5invis** [comment]
This answer may be helpful: https://stackoverflow.com/questions/51267935/uwp-console-app-with-no-icon-just-execution-alias

**Comment by MouriNaruto** [comment]
@be5invis 

I had sent a mail to Microsoft and they approved me yesterday.

So I can add this feature again.

https://github.com/M2Team/NanaZip/commit/4b8674a4bea16d06b89237deba31a12656c32f3c

**Comment by MouriNaruto** [comment]
NanaZip 1.0 Preview 2 has been released to GitHub, and I have submitted to the Windows Store and wait for the certification.

https://github.com/M2Team/NanaZip/releases/tag/1.0-Preview2

So, I think it's time to close the issue. If you have met the same issue. Feel free to reply to this issue and I will open it again.

Kenji Mouri

**Comment by MouriNaruto** [comment]
@be5invis 

NanaZip 1.0 Preview 2 has been submitted to the Windows Store now successfully.

This issue is finally resolved.

Kenji Mouri

**Comment by curly-wei** [comment]
To use CLI, where the path I should add into *PATH* of environment variable?

**Comment by AndromedaMelody** [comment]
Reply https://github.com/M2Team/NanaZip/issues/4#issuecomment-1279992626 (@curly-wei) : NanaZip is packaged by MSIX, so this means NanaZip uses AppModel. As a result, we can't add it into PATH of environment variable, and you can only set a app execution aliase. For example(Win 11 22H2 Build 22621), Settings(UWP App) -> Apps -> Advanced app settings -> App execution aliases. Thanks for your support.
