### ISSUE TITLE
Mica dark mode font is illegible when HDR/ACM enabled

### ISSUE THREAD

**Issue by Andarwinux** [M2Team/NanaZip#402]
![image](https://github.com/M2Team/NanaZip/assets/144242044/d14a74b5-b67a-4fb6-9e97-b8a638036fb6)

**Comment by MouriNaruto** [comment]
It seems that it should be the DWM blur issue.

I also want to know if the Mica dark mode is OK when HDR/ACM is not enabled.

I will workaround that according to your answer of the question I asked.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Thank you very much. I think I will make the workaround that with the following policies:

- The legacy UI parts of NanaZip will not use the Mica effect in the dark mode if the HDR/ACM is enabled, except the title bar.
- If I have migrated the Win32 menu bar and Win32 toolbar to the new XAML-based command bar in the main window, I will use Mica for the title bar and XAML-based command bar.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have tried to add the HDR/ACM check for workaround this issue.

I hope you can test the latest commit. Thanks.

Kenji Mouri

**Comment by graphixillusion** [comment]
I'm just tring the new 3.0 version and with the dark theme i have a strange behaviour: all the text in the interface have somekind of bold text effect, when the mouse cursor goes over it, the bold's effect is removed and the text becomes normal.

**Comment by PowerRangerX** [comment]
> Thank you very much. I think I will make the workaround that with the following policies:
> 
>     * The legacy UI parts of NanaZip will not use the Mica effect in the dark mode if the HDR/ACM is enabled, except the title bar.
> 
>     * If I have migrated the Win32 menu bar and Win32 toolbar to the new XAML-based command bar in the main window, I will use Mica for the title bar and XAML-based command bar.
> 
> 
> Kenji Mouri

I hope you don't mean these means because these are fantastic, wonder why msft doesn't do it to legacy parts of Windows.

![Screenshot 2024-05-23 013638](https://github.com/M2Team/NanaZip/assets/85272502/28dc72d6-0f35-4c3d-b124-4c5170cb20d8)
