### ISSUE TITLE
XAML Islands的tooltip阴影无Mica效果

### ISSUE THREAD

**Issue by WhatDamon** [M2Team/NanaZip#414]
问题见上，截图如下
此问题在暗黑模式下尤为明显
![image](https://github.com/M2Team/NanaZip/assets/59256766/ba151e60-02e5-4ffa-9105-0cfa42fb8a7f)

类似的问题在设置界面的Win32下拉菜单也可以看到

**Comment by MouriNaruto** [comment]
这个属于已知问题，而且是 Windows 10 下没有问题，Windows 11 有相关问题的情况
总之得思考解决方案

毛利

**Comment by MouriNaruto** [comment]
这个问题刚刚偶然找到了一个解决方案，已经提交到主线，你可以自己编译源码尝试尝试

https://github.com/M2Team/NanaZip/commit/2603e8e373e23c38c37a5fc1b243970796109e74

毛利

**Comment by win98se** [comment]
![image](https://github.com/M2Team/NanaZip/assets/11819816/610d0fb4-5b0e-45b8-91b4-a7c1bf03a813)
在我这里看来是解决了（版本3.0.1000.0/3.5.1000.0），请@WhatDamon协助验证

**Comment by WhatDamon** [comment]
![image](https://github.com/M2Team/NanaZip/assets/59256766/d7d02ecb-a5fc-4720-9714-d51f76acb61d)
已经得到修复，将Close本issue
