### ISSUE TITLE
[Appearance] Transparency effect not work when Auto Color Management on

### ISSUE THREAD

**Issue by hluica** [M2Team/NanaZip#427]
Even if the HDR is disabled, the transparency effect (mica) of the background will not work if the Auto Color Management is turned on from `Settings > System > Display > Advanced display`.

- Auto Color Management ON: no transparency effect
![屏幕截图 2024-05-27 234700](https://github.com/M2Team/NanaZip/assets/136835843/1610135a-93b4-4837-8ec8-aecd29f9013c)

- Auto Color Management OFF: expected behavior
![屏幕截图 2024-05-27 234552](https://github.com/M2Team/NanaZip/assets/136835843/c7763926-0f1a-493b-923b-06dc366d3203)

I guess, this is because ACM and HDR both use Advanced Color to support larger color gamuts than sRGB.

**Comment by MouriNaruto** [comment]
It's a known issue for workaround Microsoft's implementation issue.

Read https://github.com/M2Team/NanaZip/issues/402 for more information.

Kenji Mouri

**Comment by MouriNaruto** [comment]
According to https://github.com/M2Team/NanaZip#features, you will know "Support the Mica effect to the main window. **You will enjoy the full window immersive Mica for all GUI components if you are using dark mode with HDR disabled.**"

Kenji Mouri

**Comment by hluica** [comment]
I have understood that the transparency effect won't work in HDR mode, and I've realized that this won't work with ACM because of a similar cause. Now I wonder when this issue would be revised.

**Comment by MouriNaruto** [comment]
It looks HDR and ACM is the similar thing for DWM.

NanaZip will solve this issue by modernizing more UI parts with XAML, just like adding Mica support for light mode.

Kenji Mouri

**Comment by hluica** [comment]
Thanks for your answer. This issue will be closed.
