### ISSUE TITLE
The GUI show lots of vertical lines when dragging the border with mouse.

### ISSUE THREAD

**Issue by Femtometer** [M2Team/NanaZip#433]
Open:
![截图_2024-05-28_19-28-45](https://github.com/M2Team/NanaZip/assets/5461891/c3ad2449-8609-4154-acb6-8847e8ae4108)
Dragging with mouse:
![截图_2024-05-28_19-29-00](https://github.com/M2Team/NanaZip/assets/5461891/e5c5f976-f5f4-4587-a4af-40fd72fe267b)

**Comment by everything411** [comment]
same
