### ISSUE TITLE
无法后台最小化

### ISSUE THREAD

**Issue by nyakohub** [M2Team/NanaZip#47]
不知道你们有没有这种问题，无法后台解压或压缩

**Comment by nyakohub** [comment]
![微信图片_20211120234459](https://user-images.githubusercontent.com/26781505/142732526-3e745c7d-109c-45c8-836d-072b852bf371.png)
如图所示，当我解压文件时，我点击后台按钮时这个窗口应该最小化到右下角的小图标里，但是它却没有最小化，我记得之前使用其它软件会最小化的

**Comment by MouriNaruto** [comment]
@nyakohub 

> 我记得之前使用其它软件会最小化的

该经验不适用于 7-Zip 及其相关衍生版，因为对于 7-Zip 及其相关衍生版来说该按钮的作用是将当前任务优先级设置为后台任务或者前台任务。

当然 WinRAR 原版的后台前台切换按钮作用也是一模一样的。

毛利

**Comment by MouriNaruto** [comment]
@nyakohub 

虽然的确可以添加“将正在进行中的任务最小化到托盘“的功能，但是感觉缩在任务栏托盘的体验不会很好，于是我打算在 NanaZip 2.x 开发阶段重构界面的时候先试试另一种方式，即将操作中的任务显示在通知中心里面。

毛利
