### ISSUE TITLE
7-zip 21.05 released

### ISSUE THREAD

**Issue by lychichem** [M2Team/NanaZip#49]
https://www.7-zip.org/ cc@MouriNaruto

**Comment by MouriNaruto** [comment]
@lychichem 

The 7-Zip authore said `Another packages and source code will be available later.` in https://sourceforge.net/p/sevenzip/discussion/45797/thread/edcb38bbab.

So I am waiting for the source code of 7-Zip 21.05. I hope NanaZip 1.0 Preview 4 will use the 7-Zip 21.05 codebase.

Kenji Mouri

**Comment by sanderdewit** [comment]
21.06 source code;
https://www.7-zip.org/a/7z2106-src.7z

**Comment by MouriNaruto** [comment]
@sanderdewit 

Nice, I will use it as soon as possible.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I have merged 7-Zip 21.06 codebase in NanaZip. Read https://github.com/M2Team/NanaZip/commit/8b8ac31d68676ed49c2a44589c6788e2b7d37122 for more information.

Kenji Mouri
