### ISSUE TITLE
Remove the parent "NanaZip" option from Windows context menu, and allow to display any option as parent

### ISSUE THREAD

**Issue by Chaoscontrol** [M2Team/NanaZip#491]
I've done a few searches for duplicate issues. I hope I haven't missed any. 

I'd love to have "Extract here" readily available in the main level of the Windows Context menu, instead of having to dive within the Nanazip level. 99.99% of the time the single action I use is "Extract here" so I feel it quite annoying having to scroll all the way down and then find the option within the children items. 

As an extra it would be ideal if we could reorder the items and position them in the upper side of the context menu, but I guess that's a Windows 11 limitation?

![image](https://github.com/user-attachments/assets/66cb5364-b8c4-4181-87af-097c1558fbb3)

**Comment by Chaoscontrol** [comment]
I've personally moved back to the old context menu and 7-zip, which allows adding whichever actions you want directly.

**Comment by MouriNaruto** [comment]
Duplicated, read https://github.com/M2Team/NanaZip/issues/281 for more information.

Kenji Mouri
