### ISSUE TITLE
extract here option is not active

### ISSUE THREAD

**Issue by atplsx** [M2Team/NanaZip#504]
As I have reported before, the option to right-click on any archive from USB or another directory and extract here is not active. I kindly request your attention. Kind regards
![Ekran görüntüsü 2024-10-25 093329](https://github.com/user-attachments/assets/8e1cd3ee-5363-4589-b898-c91e10f6a1be)

**Comment by daf3707** [comment]
Yes, because it extracts to a directory that has not been created by default. Just delete the new directory it adds by default in the address box and you can click this button. This is indeed a BUG

**Comment by atplsx** [comment]
Thank you
