### ISSUE TITLE
Nanazip only shows in context menu for folders

### ISSUE THREAD

**Issue by bwat47** [M2Team/NanaZip#51]
After installing nanazip on windows 10 (from windows store), I see that nanazip does show in the context menu (as expected) when right clicking on a folder:

![image](https://user-images.githubusercontent.com/1442520/142884577-9e0215c5-358b-4606-b611-5acf3345b97e.png)

However, it does NOT show in the context menu when right clicking on a file:

![image](https://user-images.githubusercontent.com/1442520/142884607-84115b2e-5244-448f-b405-aa3f6170c7d3.png)

NOTE: This is the case even after restarting explorer.exe and even after rebooting the machine

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/142920955-9947805d-867b-4cb0-82de-38c4e15bbd65.png)

I can't reproduce your issue in my Windows 10 environment.

Kenji Mouri

**Comment by bwat47** [comment]
Not sure what the environmental difference could be,

I'm running 21H2 build 19044.1348

I tries creating a brand new local windows user profile but I still see the same behavior with the new windows user

**Comment by MouriNaruto** [comment]
@bwat47 

> I'm running 21H2 build 19044.1348

My Windows 10 environment is the same build.

Kenji Mouri

**Comment by komawoyo** [comment]
Nanazip in context menu is working for both old and new context menu in Windows 11. @bwat47 you might have additional tweaks that might be interfering with NanaZip. You can make sure its really a bug if you run and test on a virtual machine. Clean install. .

**Comment by bwat47** [comment]
weird... no idea what could be interfering. any other software I install (e.g. 7-zip, winrar, etc...) shows in the context menu for files without issue

**Comment by komawoyo** [comment]
@bwat47 I'm on Windows 11. For new Context Menu

**Comment by PicoPlanetDev** [comment]
![image](https://user-images.githubusercontent.com/50522829/143771131-235669cf-29ad-4da8-92bb-e089e05d4d19.png)

This actually happened to me before I rebooted my computer after installing NanaZip. After I rebooted, it worked just fine as shown above.

**Comment by Heart1010** [comment]
I have exactly the same problem than @bwat47 - on folder the context menu is there but not on files (win10).

restarted file explorer process and also did a full pc reboot - no change.

**Comment by MouriNaruto** [comment]
@Heart1010 

https://github.com/M2Team/NanaZip/issues/2#issuecomment-927323040

Kenji Mouri

**Comment by bwat47** [comment]
I have several other machines that I tried nanazip on:

one running windows 10, and atwo running windows 11, and it works fine on those machines... no idea what could be preventing it from working on this one windows 10 machine (rebooting doesn't help).

NOTE: In the problem machine, i tried the UWP files app mentioned above, and nanazip doesn't show at all in that app (doesn't matter if I right click a file or folder)... however, 7-zip does show

**Comment by bwat47** [comment]
I updated the machine in question to windows 11, and I no longer see the issue there

nanazip shows in the context menu for both files and folders, in both the new & old context menu

**Comment by SakuraNeko** [comment]
@bwat47 :

This is indeed puzzling. Do these problematic devices have similar characteristics? For example, their OS versions.

We will continue to follow up on this issue and if we find anything we will let you know here immediately.

Sakura Neko

**Comment by Heart1010** [comment]
I can only confirm @bwat47 - as said exactly same behaviour. I also tried to installed mentioned Files app above - here I also have only the NanaZip context menu when right click a folder but not when right click a file.

I had the normal 7zip version installed before trying NanaZip and uninstalled that 7zip version (7zip had the correct context menus) - eventually these old registry values from 7ip are a problem? Don't know...

Edition	Windows 10 Pro
Version	21H2
Installiert am	‎21.‎10.‎2020
Betriebssystembuild	19044.1348
Leistung	Windows Feature Experience Pack 120.2212.3920.0

**Comment by bwat47** [comment]
The one device of mine that had the problem was running windows 10 21h2

The devices that had no problems were:
2 Windows 11 devices
1 Windows 10 device (but running a build older than 21h2

The only other difference I can think of on the working devices vs the device that had the issue was that I'm fairly certain the other devices never had 7-zip installed.

That said, on the problem device, I had tried uninstalling 7-zip, using ccleaner to clean the leftover 7-zip registry entries, and rebooting and still saw the same behavior

**Comment by FadeMind** [comment]
I confirm issue. For folders menu NanaZip show up. For files nope. 

21H2 19044.1387

Even external app cannot see registry entries for menu handlers.

**Comment by AdrianDeWinter** [comment]
Me too. I have had a look at my registry permissions since i did change some of those to add options to folder context menus, but nothing is jumping out at me. Also, since the only things i changed were permissions on those keys regarding folder context menus, and those are the only ones where NanaZip does show up, i don't think that is the cause.

I can provide screenshots of those permissions if you require them.

Also:

Edition	Windows 10 Pro
Version	21H2
Installed on	‎25/‎08/‎2020
OS build	19044.1466
Experience	Windows Feature Experience Pack 120.2212.3920.0

**Comment by FadeMind** [comment]
NanaZip Preview show up context menu entries after reboot in WIndows 11. 
In Windows 10 entries was visible only for directories, not files. In Windows 11 all is fine.

**Comment by AndromedaMelody** [comment]
- Fix in #205 
- No new feedback for a long time, so we will close this issue. If the problem is found to appear again in Windows with the latest LCU, you can reopen(and comment) this issue or submit an issue.
