### ISSUE TITLE
ESET网络安全套件对NanaZip.Codecs.dll和NanaZip.Core.dll误报为Win64/Agent.AAQ木马并清除

### ISSUE THREAD

**Issue by FQDianYan** [M2Team/NanaZip#510]
ESET网络安全套件对NanaZip 3.1.1080.0的NanaZip.Codecs.dll和NanaZip.Core.dll误报为Win64/Agent.AAQ木马并清除。
ESET网络安全套件版本 18.0.12.0
ESET网络安全套件检测引擎版本 30202 2024/11/11
问题如下图

 
![屏幕截图 2024-11-11 200106](https://github.com/user-attachments/assets/862c3e0f-b064-4156-b331-4d59c756a725)

**Comment by tabtomi8** [comment]
### Can confirm this
![kép](https://github.com/user-attachments/assets/d9d4e9a3-dcc8-4e6f-ac98-7b2493c2fc3a)
**Transcription (ChatGPT):**
ESET Smart Security Premium Log

On November 11, 2024, at 15:07:46, the real-time file system protection detected two files as trojans.

1. The file NanaZip.Core.dll located at C:\Program Files\WindowsApps\40174MouriNaruto.NanaZip_3.1.1080.0_x64__gnj4mf62gtkrx was identified as a variant of the Win64/Agent.AAQ trojan. The file was cleaned by deletion.

2. The file NanaZip.Codecs.dll located at C:\Program Files\WindowsApps\40174MouriNaruto.NanaZip_3.1.1080.0_x64__gnj4mf62gtkrx was also identified as a variant of the Win64/Agent.AAQ trojan. This file was also cleaned by deletion.

**Comment by FQDianYan** [comment]
已经将被ESET误报的NanaZip.Codecs.dll和NanaZip.Core.dll作为误报样本提交给了ESET，经过测试ESET检测引擎30207（2024.11.12）已经排除了对这两个文件的误报。
