### ISSUE TITLE
[Feature] Add support for .vmdk file extension to context menu

### ISSUE THREAD

**Issue by komawoyo** [M2Team/NanaZip#52]
7zip support extraction of .vmdk files. Can add .vmdk support to context menu. 

![image](https://user-images.githubusercontent.com/18315233/143389021-70632b6f-c640-4948-b988-401b80db4926.png)

here is a picture of Nanazip opening vmdk file
![image](https://user-images.githubusercontent.com/18315233/143388897-87d93f67-757d-4d42-8cb8-c9cc35c2a52a.png)

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/143442273-d6a6bc2b-b9d1-4621-91d0-22b29537ef21.png)

It looks OK in my environment.

Kenji Mouri

**Comment by komawoyo** [comment]
Maybe I'm using old version? NanaZip_1.0.46.0.

I dont see vmdk

![image](https://user-images.githubusercontent.com/18315233/143478289-4b70829b-1b85-4113-86ac-008965251bdf.png)

**Comment by MouriNaruto** [comment]
@komawoyo The screenshot your provided to me is the file association, not the context menu.

```
        <desktop4:Extension Category="windows.fileExplorerContextMenus">
          <desktop4:FileExplorerContextMenus>
            <desktop5:ItemType Type="Directory">
              <desktop5:Verb Id="NanaZipShellExtension" Clsid="CAE3F1D4-7765-4D98-A060-52CD14D56EAB" />
            </desktop5:ItemType>
            <desktop5:ItemType Type="*">
              <desktop5:Verb Id="NanaZipShellExtension" Clsid="CAE3F1D4-7765-4D98-A060-52CD14D56EAB" />
            </desktop5:ItemType>
          </desktop4:FileExplorerContextMenus>
        </desktop4:Extension>
```

**Comment by MouriNaruto** [comment]
P.S. Original 7-Zip's file association don't provide `.vmdk` file.

Kenji Mouri

**Comment by komawoyo** [comment]
Solved the problem! 
When right clicking on the files and desktop. NanaZip context menu would show up but when I open a new folder and tried to use NanaZip it won't work. 

The problem is when "Launch folder windows in a separate process is enabled"

Maybe the .dll is not loaded on new explorer window. Might be a Windows design problem???

![image](https://user-images.githubusercontent.com/18315233/143479851-0006c985-44c3-4b13-8505-38ca77b40b0f.png)

**Comment by MouriNaruto** [comment]
@komawoyo 

> Maybe the .dll is not loaded on new explorer window. Might be a Windows design problem???

So this is why I say `If you don't find NanaZip in the context menu, please restart File Explorer via Task Manager.` in the known issues.

Kenji Mouri

**Comment by komawoyo** [comment]
"restart File Explorer via Task Manager" - this didnt work but a full Reboot worked with  "Launch folder windows in a separate process" enabled. Thanks you
