### ISSUE TITLE
How to download NanaZipPreview_5.0.1188.0.msixbundle?

### ISSUE THREAD

**Issue by H5820121** [M2Team/NanaZip#520]
At https://github.com/M2Team/NanaZip/releases/tag/5.0.1188.0
I don't see any link to download NanaZipPreview_5.0.1188.0.**msixbundle**
Thanks!

**Comment by MouriNaruto** [comment]
Waiting for Microsoft's validation. The binary will be ready when the validation passed.

Kenji Mouri

**Comment by MouriNaruto** [comment]
The msixbundle package is ready. So, I close this issue.
