### ISSUE TITLE
CLI Usage and Examples?

### ISSUE THREAD

**Issue by hl2guide** [M2Team/NanaZip#522]
Could you please offer up some examples for using `NanaZipC.exe'?

Proper documentation for this would be so useful.

I'm trying to create a Level 11 zstandard compressed 7z archive and so far I have:

```
NanaZipC.exe a -m:zstd "I:\Temp\test.7z" "J:\Backups\AdGuardHome.yaml"
```

but I get the output:

```
NanaZip 3.1 (x64) : (c) M2-Team and Contributors. All rights reserved.

Scanning the drive:
1 file, 27533 bytes (27 KiB)

Creating archive: I:\Temp\test.7z



System ERROR:
The parameter is incorrect.
```

NanaZip version: 3.1.1080.0 (x64)

**Comment by MouriNaruto** [comment]
The usage of NanaZipC should be the same as 7-Zip command line version.

Kenji Mouri
