### ISSUE TITLE
文件管理器中无法筛选7z和rar中的某一种文件

### ISSUE THREAD

**Issue by oxygen-dioxide** [M2Team/NanaZip#53]
把7z和rar文件均设为用nanazip打开，则文件类型均显示为“NanaZip Archive”，且无法筛选其中一种文件
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54425948/143565101-87333539-55b5-49d2-9f9c-18f5233680d5.png">

但如果均改为用7zip打开，则文件类型分别显示为“7Z 文件”和"RAR 文件"，可以分别筛选。
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54425948/143564905-0b3c42a2-7621-4489-a60c-050edb2e96cd.png">
<img width="506" alt="image" src="https://user-images.githubusercontent.com/54425948/143565340-530e53ac-ac5b-4ea5-ab0b-c7e51f678ea1.png">

**Comment by MouriNaruto** [comment]
感谢反馈，在下一个 NanaZip 版本中会解决该问题。

毛利

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/143582575-b8610b80-43e7-4dc5-bebc-12c1e6901055.png)

问题解决，遂关闭问题。

https://github.com/M2Team/NanaZip/commit/22a6643ec425f1c451dd5cbc206ee9bc1cb41a60

毛利
