### ISSUE TITLE
.webp as archive file

### ISSUE THREAD

**Issue by Zbynius** [M2Team/NanaZip#57]
In the Nana Zip context menu for *.webp files there is a command "Open archive". Clicking causes an error.

**Comment by MouriNaruto** [comment]
I have reproduced it and will try to fix it in the recent days.

**Comment by MouriNaruto** [comment]
Fix it in https://github.com/M2Team/NanaZip/commit/749cbf7ca6f186d0e21038c5fa7f760f65bf7c9f.

Kenji Mouri
