### ISSUE TITLE
Add install instructions

### ISSUE THREAD

**Issue by wallrik** [M2Team/NanaZip#58]
If you want a pull request, I can do it, but I just thought I'd share my use-case.

I have early on removed almost all AppX packages from my Windows installation to "de-bloat" my Windows.

This means when I download an `.msixbundle` the file extension is not associated with any application. I can't just _run_ it as instructed in the release notes.

I have to run PowerShell and run:
```ps
Add-AppxPackage ./40174MouriNaruto.NanaZipPreview_1.0.88.0_gnj4mf6z9tkrc.msixbundle
```

It installs just fine after that, so maybe that's good to add to the README file. 👍

**Comment by MouriNaruto** [comment]
The install instructions is in the GitHub Release page because every version will have a different file name.

But I will provide NanaZipInstaller.exe for users who want to install it without Windows Store to simplify the install experience.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I think https://github.com/M2Team/NanaZip#download-and-installation will follow your suggestion.

Kenji Mouri
