### ISSUE TITLE
Nanazip解压缩性能测试评分低于7-zip

### ISSUE THREAD

**Issue by everything411** [M2Team/NanaZip#60]
版本：7zip 21.06和Nanazip 1.0 Preview4，大内存页开启
系统环境：Intel i5-8300H，Windows 11 x64
Nanazip
![nanazip](https://user-images.githubusercontent.com/32010059/144774946-cf58a426-d8b6-45a6-b82d-c89da3e75f37.png)
7-zip
![7zip](https://user-images.githubusercontent.com/32010059/144774972-f017f3b9-4eca-4fc1-bf17-4532e9686a30.png)

此问题在我的另一台机器AMD R5-3550H同样出现

**Comment by MouriNaruto** [comment]
为了可移植性考量当时没有使用 7-Zip 提供的汇编代码，估计在 NanaZip 1.1 阶段我会试着把这些内容添加回来，也许会有所改善。

毛利

**Comment by MouriNaruto** [comment]
![image](https://user-images.githubusercontent.com/10867563/146567952-f059473e-bdae-49be-97d7-2eb240953140.png)

果然是没上 7-Zip 提供的汇编代码的缘故……

毛利

**Comment by MouriNaruto** [comment]
这是解决本 issue 的对应提交
https://github.com/M2Team/NanaZip/commit/3916f87c06d657133db3a198b1645ce693ff2ec4

按照 @SakuraNeko 的测试情况，在基准测试页面的确有了不小的提升

毛利
