### ISSUE TITLE
希望能够使用7zip的文件类型关联功能

### ISSUE THREAD

**Issue by hingbong** [M2Team/NanaZip#62]
Windows11上在系统设置关联比较麻烦，还缺少某些类型的关联，例如`.jar`，希望能够使用类似7-zip的在软件菜单可以直接把类型关联上

**Comment by MouriNaruto** [comment]
由于 Windows 10/11 桌面桥应用模型限制且 NanaZip 不想和微软斗智斗勇，于是文件关联功能请使用 Windows 的设置 App 中的相关功能，如果 Windows 相关的设置功能用得比较麻烦，请直接向微软反馈。

毛利

**Comment by hingbong** [comment]
也猜到可能是这个原因，微软是真的寄

**Comment by AndromedaMelody** [comment]
Fix in #312
