### ISSUE TITLE
Preview channel should receive also stable versions

### ISSUE THREAD

**Issue by maicol07** [M2Team/NanaZip#68]
Hi,

the Preview channel should receive also the stable versions of NanaZip, when they are newer than the last preview.

Example: 1.0 is versioned after 1.0 Preview 4 and is technically more recent

**Comment by MouriNaruto** [comment]
I will release 1.1 Preview 1 as soon as possible for solving this.

Kenji Mouri

**Comment by MouriNaruto** [comment]
NanaZip 1.1 Preview 1 has been submitted to the Windows Store successfully.

https://github.com/M2Team/NanaZip/releases/tag/1.1-Preview1

Kenji Mouri
