### ISSUE TITLE
LIZARD算法无法使用

### ISSUE THREAD

**Issue by ktns01** [M2Team/NanaZip#71]
我试图用LIZARD算法进行压缩操作，但最后提示说函数不正确。
操作系统是Windows 11 家庭中文版 Build 22000.348，CPU是5600H。下图是我使用的设置和弹出的错误。
<img width="470" alt="屏幕截图 2021-12-10 130928" src="https://user-images.githubusercontent.com/93424632/145520764-658dde77-4e83-4834-958b-8041042f5473.png">
<img width="127" alt="屏幕截图 2021-12-10 130945" src="https://user-images.githubusercontent.com/93424632/145520780-4cd35507-60be-42f8-a0bb-e7a5be97e9b7.png">
请问是我的设置不对还是BUG？

**Comment by MouriNaruto** [comment]
属于已知问题，该算法从 7-Zip ZStandard 分支继承，而该分支的最新版本也是存在该问题的，需要等待上游解决。

毛利

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NanaZip/commit/3f10b7def229968b4066ef8f405860a82fe86833

上面的 commit 应该是修复了你提到的问题，请耐心等待下一个 NanaZip 版本的发布，遂本问题被关闭

毛利
