### ISSUE TITLE
Feature Request: Custom Icon Support

### ISSUE THREAD

**Issue by HylianSteel** [M2Team/NanaZip#74]
For a couple years now, I've been using a nifty utility called 7-Zip Theme Manager to change the icons of supported filetypes.
Would it be possible if you could add in theming support for icons into NanaZip?

**Comment by MouriNaruto** [comment]
Reference: https://github.com/M2Team/NanaZip/issues/38

Due to the mechanism of App Model, NanaZip is unable to implement that.

If you wonder to change icons. You need to repack the msix package like adding Magisk to Windows Subsystem for Android.

Kenji Mouri
