### ISSUE TITLE
Context Menu cannot display

### ISSUE THREAD

**Issue by taooceros** [M2Team/NanaZip#76]
![image](https://user-images.githubusercontent.com/45326534/145829050-7ab9042a-2ec5-4b66-a4d1-9eb556443ed4.png)
![image](https://user-images.githubusercontent.com/45326534/145829090-04d72c25-83b6-4511-8832-6e28f065fcc7.png)

Restart Windows Explorer doesn't work (have tried restarting computer)

System Version: 21H2
System Build: 22000.348
Edition: Windows 11 Education

**Comment by MouriNaruto** [comment]
NanaZip only shows the context menu when you right click for file or directory, not right click the desktop.

https://user-images.githubusercontent.com/10867563/139175377-ec1f1a04-eb01-4dee-af2c-c86d889f7e3f.png

Kenji Mouri

**Comment by taooceros** [comment]
Oh thank you for clarifying!
