### ISSUE TITLE
The toolbar icon is blurred on HiDPI screens

### ISSUE THREAD

**Issue by skyline75489** [M2Team/NanaZip#81]
很感谢 M2Team 的辛苦工作，谢谢你们！

### Screenshot

![屏幕捕获_2021_12_20_11_49_01_586](https://user-images.githubusercontent.com/4710575/146709195-612a74f3-0865-48c4-8fb3-dff97c257eb7.png)

**Comment by MouriNaruto** [comment]
由于 Win32 工具栏控件的局限性（只支持位图），于是我当时尽力（考虑到素材体积和清晰度等）搞成了当前的样子

当然这部分会在 NanaZip 2.x 阶段改成基于 XAML Islands 的 XAML CommandBar 的实现，里面会直接采用来自 Segoe Fluent Icons 的矢量图标（其实现在的图标也是基于这个矢量图标按照特定尺寸生成的位图），就不会有这样的问题了

其实这个也在之前的 issue 提到过：https://github.com/M2Team/NanaZip/issues/55#issuecomment-985570312

毛利
