### ISSUE TITLE
貌似对于分割文件支持不够

### ISSUE THREAD

**Issue by 1human** [M2Team/NanaZip#82]
下载了一个分割的压缩包，文件显示解压错误
winrar正常

另外夸一下，非常漂亮的UI！

**Comment by MouriNaruto** [comment]
希望能够提供能加详细的信息方便确定并解决问题

**Comment by 1human** [comment]
![Snipaste_2021-12-20_23-22-37](https://user-images.githubusercontent.com/18576031/146790975-2436fa7e-1516-4133-8938-67ba6724c448.png)
这是同一个分割的压缩文件 winrar和nanazip的对比
nanazip显示的文件是不全的
直接解压后也会出错
不知道这算不算添加更多信息了

**Comment by MouriNaruto** [comment]
@1human 如果能提供资源的下载链接就更好了（方便我做相关测试）

毛利

**Comment by 1human** [comment]
@MouriNaruto 
大佬，我把文件传迅雷网盘了，如果你想测试的话。
就是文件有点大，有13g左右

链接：https://pan.xunlei.com/s/VMrL0_zl3iIyz8sh4IXMcBhFA1
提取码：k7ic

**Comment by MouriNaruto** [comment]
@1human 看起来当我想下载的时候已经过期了……
![image](https://user-images.githubusercontent.com/10867563/146869497-5696489b-4b92-4bcd-a856-ff09be3487c7.png)

毛利

**Comment by 1human** [comment]
@MouriNaruto 
尴尬了
链接：https://pan.xunlei.com/s/VMrQB2MclV4tHihDZgMXgK9PA1
提取码：ydsq
再来一次

**Comment by MouriNaruto** [comment]
@1human 

看起来是 NanaZip 继承的 7-Zip 实现中的探测 RAR 分卷文件名的实现没有 WinRAR 那么智能，这个问题我会尝试解决

临时解决方案：将这些分卷压缩包的文件名中 `_Downloadly.ir` 这段去掉，以形成类似 .part*.rar 的形式即可解决

![image](https://user-images.githubusercontent.com/10867563/146873592-05bb56b4-ff22-4600-ac8a-037c966dbdfd.png)

毛利

**Comment by 1human** [comment]
啊，原来这么简单就能解决。。。
感谢大佬

**Comment by MouriNaruto** [comment]
@1human 

前段日子试着写了个比较粗糙的修复方式然后给 7-Zip 发了个 patch

https://sourceforge.net/p/sevenzip/patches/380/

7-Zip 作者会尝试修复，相关问题会继续跟踪

毛利

**Comment by MouriNaruto** [comment]
https://github.com/M2Team/NanaZip/commit/ec7eaf3b9376e9426ca2ed573a19419846b907db

NanaZip 这边也做了相关修复（最近事情比较多，而且验证花了一些时间）

最近会发布下一个 Preview 版，到时候你可以体验下修复后的结果

毛利

**Comment by MouriNaruto** [comment]
由于 1.1 Preview 2 已发布半个月且没有后续反应，暂时认为问题已经解决，遂关闭问题

毛利
