### ISSUE TITLE
Association settings

### ISSUE THREAD

**Issue by soredake** [M2Team/NanaZip#83]
Original 7zip have settings to associate specific or all formats with 7zip, would be nice to have this in nanazip.
![изображение](https://user-images.githubusercontent.com/5204968/146801478-fab5a031-ab6a-464b-8ca1-96da4ba406b5.png)

**Comment by MouriNaruto** [comment]
We need to follow the rules from Microsoft. So, NanaZip only use file association settings in Windows Settings app.

Reference: https://github.com/M2Team/NanaZip/issues/62

Kenji Mouri

**Comment by soredake** [comment]
@MouriNaruto 
https://github.com/stax76/mpv.net/blob/243b45326ef8defa038edacd01fafee13f6a009a/src/Misc/Commands.cs#L473-L506
Can't nanzip include similar script/code to register associations?

**Comment by AndromedaMelody** [comment]
- This comment is converted from discussion (@bacevs discussed in [#253](https://github.com/M2Team/NanaZip/discussions/253)).
- For more information, please read #274. Thank you.

> ## Bring back file "associate" within app like 7Zip.
> <sup>Originally posted by **@bacevs** December 10, 2022</sup>
> The windows default way of doing things is pretty tedious way of setting defaults. 
> Could you bring back the in-app associate setting like 7zip has?  
> 
> ![associate](https://user-images.githubusercontent.com/1433845/206840976-27fd01ac-ee74-4049-9df9-5f9ec7390023.png)

**Comment by AndromedaMelody** [comment]
Fix in #312

**Comment by AndromedaMelody** [comment]
> I'm not sure I understand, does the fix in [#312](https://github.com/M2Team/NanaZip/pull/312) mean this change was made, and nanazip has the association tab like in 7zip?

@MouriNaruto https://github.com/M2Team/NanaZip/issues/62#issuecomment-989458336

Due to the limitations of the Windows 10/11 desktop bridge application model, there is no documented API to set association.

**Comment by bacevs** [comment]
This still bugs me, and is a reason why I keep using 7zip on fresh PC installs
