### ISSUE TITLE
7-Zip 21.07

### ISSUE THREAD

**Issue by HylianSteel** [M2Team/NanaZip#85]
This is probably not the best way to notify you... and you may not have needed to be notified at all, but 7-Zip has been updated to 21.07.
https://sourceforge.net/p/sevenzip/discussion/45797/thread/0a7b47970b/
If notifying you in this manner is not wanted or needed, I will refrain from doing so in the future.

**Comment by MouriNaruto** [comment]
Thank you for notifying me. I have updated to 7-Zip 21.07 codebase just now.

https://github.com/M2Team/NanaZip/commit/5615db171fe8faca06d064b05369f385a270b655

Kenji Mouri

**Comment by Neustradamus** [comment]
@MouriNaruto, @HylianSteel: There is old requests to move 7-Zip on GitHub, maybe you can help, 10 years already.

**Comment by MouriNaruto** [comment]
@Neustradamus 

> There is old requests to move 7-Zip on GitHub, maybe you can help, 10 years already.

https://github.com/M2Team/NanaZip/issues/1#issuecomment-927255497

Kenji Mouri

**Comment by Neustradamus** [comment]
@ all: It is linked to:
- https://sourceforge.net/p/sevenzip/feature-requests/1028/
- https://sourceforge.net/p/sevenzip/feature-requests/1169/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/6307c6fd/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/7a122fc2/
- https://sourceforge.net/p/sevenzip/discussion/45797/thread/fa951551/

Please comment on it...
