### ISSUE TITLE
Unable to allocate enough memory

### ISSUE THREAD

**Issue by Thane5** [M2Team/NanaZip#87]
I was trying to compress the game files of Witcher 3 into a 7z archive, but after a few seconds NanaZip would show an error about being unable to allocate enough memory for this operation. 

- The uncompressed files are about 33GB
- i have 32GB of RAM
- I tried to do the same with the latest release of 7-zip, which did not have the issue. While compressing the files 7-zip only needed just above 1,8GB of RAM. 
- Tested using Windows store preview version on Windows 11.

**Comment by MouriNaruto** [comment]
Can you provide the screenshots of "add to archive" options dialog and error dialog.

**Comment by Thane5** [comment]
Context menu option i used:
![Screenshot 2022-01-02 170035](https://user-images.githubusercontent.com/13683581/147881518-a55e76ed-fbdf-46c1-8263-091e2014a717.png)

Error message:
![Screenshot 2022-01-02 165835](https://user-images.githubusercontent.com/13683581/147881456-d76b3319-74bd-456b-89d3-356ec095467d.png)

**Comment by MouriNaruto** [comment]
@Thane5 

Got it.

But which the compression level you have chosen? For example, I wonder to see the screenshot like that.
![image](https://user-images.githubusercontent.com/10867563/147881816-a6faa3d2-4e17-4414-8bed-282fe38b1c80.png)

Kenji Mouri

**Comment by Thane5** [comment]
I didn't change any settings, so i guess this should be the ones it uses:
![Screenshot 2022-01-02 172010](https://user-images.githubusercontent.com/13683581/147882134-8a3c6e37-9d6e-486f-b1fe-
7e42535b9398.png)

**Comment by MouriNaruto** [comment]
@Thane5 

Got it. I will try to reproduce it.

Kenji Mouri

**Comment by Zriel88** [comment]
Got the same issue
16GB of RAM
Issue comes when you try to compress a big enough file (a 38GB file in my case)
RAM is filled up completely and then the compression crashes.

**Comment by Merowinger86** [comment]
Same here. It happens only sometimes when I try to create an archive via the context menu without opening the extended archive creation dialog. When I use the dialog, it works perfectly fine. It't not even a big bunch of files, just a folder with mp3s, 270 MB.

![Unbenannt 1](https://user-images.githubusercontent.com/104984893/167439441-2832a49f-7783-4890-a0ad-4ee8d936f0c2.jpg)
