### ISSUE TITLE
NanaZip missing in Right-click drag menu

### ISSUE THREAD

**Issue by Thane5** [M2Team/NanaZip#88]
7-Zip has this nice feature where you can drag a folder with the right mouse button, then on release it will show the usual context menu options to create a new compressed archive on the location where you released the mouse.
![image](https://user-images.githubusercontent.com/13683581/147890166-14f40fac-dc87-47ac-87a3-6fcbd94ba3a5.png)

Of course since Windows 11 is made by Microsoft, this menu still uses the old context menu from pre-windows 11. 
I guess since NanaZip uses the new context menu technology, it is missing from here. 

Do you think there is a chance you can add this menu entry back, until Microsoft updates it to the new context menu system?

**Comment by MouriNaruto** [comment]
It's a duplicated issue.

Here is the reference: https://github.com/M2Team/NanaZip/issues/13.

Kenji Mouri
