### ISSUE TITLE
Filetype Icon Suggestion

### ISSUE THREAD

**Issue by lychichem** [M2Team/NanaZip#9]
Now the icon of the program is same for all supported filetypes. And they don't fit well with original WIndows 10 and Windows 11 theme.
Here I suggest using new themes for widows 10 and windows 11:
For Windows 10: [7-Zip Filetype Theme - Windows 10 by masamunecyrus](https://www.deviantart.com/masamunecyrus/art/7-Zip-Filetype-Theme-Windows-10-550864748)
![image](https://user-images.githubusercontent.com/9316590/135698643-31e40112-7d91-4507-9eb8-537cd258f3c7.png)

For Windows 11: [Windows 11 Theme by ivan13x](https://www.deviantart.com/ivan13x/art/Windows-11-Theme-885090687)
![image](https://user-images.githubusercontent.com/9316590/135698650-ae64b9d8-31ab-4047-beea-de873d746375.png)

You can also consider using the toolbar icon from the same users. Great thanks if you can consider my suggestion.

**Comment by SakuraNeko** [comment]
Thank you very much for your suggestion.

Considering the size of the software (adding multiple icons of split files may increase the size of the software). At this stage, we don't think this is a necessary feature.

Of course, if more users make similar suggestions, we may decide whether to add multi-file icons eventually in light of the actual situation.

SakuraNeko

October 2, 2021

**Comment by MouriNaruto** [comment]
@lychichem 

> Great thanks if you can consider my suggestion.

I think we should not use these icons unless we are authorized by the authors of these icons. It's important. For example, some colorful icons used in Windows File Explorer is SVG assets used internally by Microsoft.

So I think we, the development team of NanaZip, can make more communications to the current art designer, to follow the Microsoft Fluent Design standards better.

Kenji Mouri

**Comment by MouriNaruto** [comment]
I think it's time to close the issue because we need a long time to improve the icon design.

Kenji Mouri
