### ISSUE TITLE
Open folder after extracting

### ISSUE THREAD

**Issue by b-** [M2Team/NanaZip#93]
I heavily rely on the "Open destination folder after extracting" feature in archiving tools, but it looks like this was removed in NanaZip. Could I please request an option for this feature?

**Comment by MouriNaruto** [comment]
Duplicated: https://github.com/M2Team/NanaZip/issues/44

Kenji Mouri

**Comment by b-** [comment]
Sorry, I didn’t see the open issue. Thanks!

**Comment by MouriNaruto** [comment]
@b- 
That issue I have closed because I have add this feature to the development roadmap.

Kenji Mouri
