### ISSUE TITLE
Moving explorator's middle bar creates visual glitches

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#95]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

When moving the middle bar of the explorer the view glitches - the second view isn't shown and the bar itself disappears.

Reproduction steps:
1. Turn on the 2 panels view
2. Click the middle bar and move it quickly to the left and right

Expected result: the view gets shortened/widened without any glitches

Real result:
![image](https://user-images.githubusercontent.com/39709348/149836832-39a0bbc2-adcb-4c2b-80dc-97199b7ea3d9.png)

Used version: NanaZip 1.0

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. So fixing all of bugs in legacy UI is meaningless. Rebuilding XAML UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
