### ISSUE TITLE
Selection box doesn't work as intendent

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#96]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

Selection box doesn't select files properly:

![image](https://user-images.githubusercontent.com/39709348/149839888-5c364270-a009-4467-9c97-ac6446353f9a.png)

Expected result: All files should be selected

Version: NanaZip 1.0 x64

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Rebuilding XAML UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
