### ISSUE TITLE
Apply button in options doesnt work

### ISSUE THREAD

**Issue by mateuszbasiak** [M2Team/NanaZip#98]
Together with @JKolodziejczyk and @apospieszny, we have been testing NanaZip as the final project for the Software Testing course at Jagiellonian University. Here is one of our results:

When changing options and clicking apply button changes doesn't apply

Reproduction steps:
1. Open the options menu and go to the Language tab
2. Change language
3. Click apply

Expected result: Language should change immediately

Real result: Language changes after closing the menu: it doesn't matter whether we click an ok button or cancel button

Used version: NanaZip 1.0 x64

**Comment by AndromedaMelody** [comment]
This is a bug of legacy UI. 

NanaZip will use Mile.Xaml (XAML Islands tool) to rebuild UI, like About Dialog in NanaZip 2.0. ***So fixing all of bugs in legacy UI is meaningless.*** Rebuilding XAML UI is a epic project, please wait for new UX patiently. 

As a result, we are sorry to close this issue. For more information about new UI, You can pay attention to the pinned issue, roadmap and release notes. 

About New UI, you can discuss here:
- #5

Thanks for your support and understanding.
